feat(monaco): add theme hook
Codecademy/gamut pull request #1915
Opened 2021-07-23 13:58 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-07-23 18:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.765e13.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-23 18:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fb0b9ad6a9dc09fd578bcb--gamut-preview.netlify.app>https://60fb0b9ad6a9dc09fd578bcb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fb0b9ad6a9dc09fd578bcb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-23 21:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.ff25a7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-23 21:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://60fb363124ae623d32140ec1--gamut-preview.netlify.app>https://60fb363124ae623d32140ec1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/60fb363124ae623d32140ec1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-28 16:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.0.2-alpha.f71ab5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-28 16:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6101854a02a53349f7c5a637--gamut-preview.netlify.app>https://6101854a02a53349f7c5a637--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6101854a02a53349f7c5a637>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-28 18:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.1.1-alpha.485725.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-28 18:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6101a52dfe672b1fb5701f68--gamut-preview.netlify.app>https://6101a52dfe672b1fb5701f68--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6101a52dfe672b1fb5701f68>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-07-28 22:47 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/index.tsx
>    // TODO import editor theming and settings hooks
```suggestion
  // TODO import editor settings hook
  
```

2021-07-28 22:49 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +}
This is actually new to me. @aionate0812 @casey-speer why not always go with the 'dynamic' theme, and have it be part of learner settings? Why would we want to explicitly override?

I'm not positive this should be ported to the shared module. I'd think the module want not want to know of such a difference, and instead be told its theme by the parent app.

2021-07-28 22:49 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +  // TODO get user interface settings
?

2021-07-28 22:50 UTC, JoshuaKGoldberg commented on packages/monaco/src/libs/services/styles.module.scss
> +.lintDecoration {
bbllllurrrgghhhh this whole thing.

@dreamwasp @codecaaron is there a way to generate a class name in our Emotion / gamut-styles land? I forget...

2021-07-28 22:50 UTC, JoshuaKGoldberg commented on packages/monaco/src/libs/theme/colorsLEThemed.ts
> +// TODO: get from learner settings when available
?

```suggestion
```

2021-07-28 22:53 UTC, JoshuaKGoldberg reviewed
I am surprised by there being a difference between LE and colors?

But since this is how it is in the monolith I think the only blocking-ish question for me is about the class names.

2021-07-28 22:53 UTC, JoshuaKGoldberg commented on packages/monaco/src/libs/theme/colorsLEThemed.ts
> +    attribute: getColorValue(theme.modes[colorMode]['editor-attribute']),
Nit: I feel like you could deduplicate these to be a little less verbose...

```ts
const getColorValue = (color: string) => theme.getColorValue(theme.modes[colorMode][color]);
```

2021-07-29 19:00 UTC, aionate0812 commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +  // TODO get user interface settings
not relevant anymore, removed

2021-07-29 19:01 UTC, aionate0812 commented on packages/monaco/src/libs/theme/colorsLEThemed.ts
> +    attribute: getColorValue(theme.modes[colorMode]['editor-attribute']),
typescript was not happy

2021-07-29 19:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.1.1-alpha.f79768.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-07-29 19:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6102fbd961c2715ebe5013f6--gamut-preview.netlify.app>https://6102fbd961c2715ebe5013f6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6102fbd961c2715ebe5013f6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-09 14:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.2.1-alpha.1492b6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-09 14:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61113d284f319f8af6fcee6d--gamut-preview.netlify.app>https://61113d284f319f8af6fcee6d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61113d284f319f8af6fcee6d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-17 12:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.2.1-alpha.7d826e.0<br/>@codecademy/styleguide@43.7.4-alpha.7d826e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-17 12:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611bb04d29a61020086dea2d--gamut-preview.netlify.app>https://611bb04d29a61020086dea2d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611bb04d29a61020086dea2d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-17 17:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/monaco@0.2.1-alpha.31ca91.0<br/>@codecademy/styleguide@43.7.4-alpha.31ca91.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-08-17 17:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://611bf167380b270e0e3076fc--gamut-preview.netlify.app>https://611bf167380b270e0e3076fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/611bf167380b270e0e3076fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-08-20 15:23 UTC, judahtanthony commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +      monaco.editor.setTheme(EditorTheme.dark);
Can you help me understand this?  My assumptions:
1. defineTheme creates a name to config mapping.
2. setTheme activates a theme based on the previously defined name.
3. CodecademyTheme is one of darkTheme or lightTheme based on user context.
If that is the case, why aren't we just defining both light and dark, and then doing the `themeType===MonacoThemeType.static ...` when we are setting/choosing the theme?  If my assumptions are true, you might actually be giving the lightTheme the name EditorTheme.dark, just so we can show it.

2021-08-20 15:27 UTC, judahtanthony commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +      monaco.editor.setTheme(EditorTheme.dark);
hmmm.  looking at packages/monaco/src/libs/theme/editorTheme.ts, it looks like my assumptions are off.  There is not lightTheme.

2021-08-20 15:29 UTC, judahtanthony commented on packages/styleguide/stories/Molecules/MonacoEditor.stories.mdx
> +        <MonacoEditor {...args} />
Woohoo.  I'm so glad you were able to get this in storybook.

2021-08-20 15:56 UTC, judahtanthony reviewed
There is something slightly strange going on with this element on the right side, but I don't know if it is actually a bug.
<img width="1258" alt="Screen Shot 2021-08-20 at 11 53 32 AM" src="https://user-images.githubusercontent.com/578710/130260478-1e3248fa-a75a-41a0-9993-6d436e375238.png">

Also the readOnly prop in storybook doesn't seem to actually prevent you from altering the contents of the editor.  Am I mistaking the meaning of this?

2021-08-24 20:26 UTC, JoshuaKGoldberg requested changes
LGTM in general, thanks for the great coverage & docs!

Just waiting on the pending threads 👍

2021-08-24 20:26 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/index.tsx
> +export const defaultUserInterfaceSettings: EditorInterfaceSettings = {
Nit:

```suggestion
const defaultUserInterfaceSettings: EditorInterfaceSettings = {
```

2021-08-24 20:26 UTC, JoshuaKGoldberg commented on packages/monaco/src/MonacoEditor/types.ts
> +export type EditorFontSize = 'reg' | 'lg' | 'xl';
Can this be taken in from the Monaco types? Seems like it's one of theirs, no?

And why would we allow this? Are all of our editors not using the same font size?

2021-09-01 21:30 UTC, casey-speer commented on packages/monaco/src/MonacoEditor/useEditorTheming/index.ts
> +  // TODO add useEffect to update high contrast
What's up with this?

2021-09-01 21:30 UTC, casey-speer commented on packages/monaco/src/libs/theme/colorsLEThemed.ts
> +import { platformTheme as theme } from '@codecademy/gamut-styles';
Similar to the points raised above, this is pretty monolith-specific at present. I guess this is kind of a philosophical point for now, but are `platformXXX` things intended as anything connected to the LE (as opposed to monolith-only)? Do we intend to have the code editor connected to the LE whenever we use it, or are there cases where we might want to use it standalone?  If the answer to either of those questions is "no", then we might not want to couple to platform-specific styles in this package.

2021-12-27 16:00 UTC, JoshuaKGoldberg commented
Closing as aged away. I'll be continuing this push in January. Thanks!

2021-12-27 16:00 UTC, closed without merging