feat(GlobalHeader): Accessible GlobalHeader!
Codecademy/gamut pull request #2179
Opened 2021-11-17 00:39 UTC by thedoomshine

### Overview

### PR Checklist

- [ ] Related to designs:
- [X] Related to JIRA ticket: [GM-364](https://codecademy.atlassian.net/browse/GM-364)
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2021-11-18 00:24 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.669496.0<br/>@codecademy/gamut-labs@28.0.12-alpha.669496.0<br/>@codecademy/gamut@40.3.3-alpha.669496.0<br/>@codecademy/monaco@0.5.13-alpha.669496.0<br/>@codecademy/styleguide@50.2.4-alpha.669496.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-18 00:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61959da7f9e738494e46c270--gamut-preview.netlify.app>https://61959da7f9e738494e46c270--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61959da7f9e738494e46c270>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-18 00:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.6704a4.0<br/>@codecademy/gamut-labs@28.0.12-alpha.6704a4.0<br/>@codecademy/gamut@40.3.3-alpha.6704a4.0<br/>@codecademy/monaco@0.5.13-alpha.6704a4.0<br/>@codecademy/styleguide@50.2.4-alpha.6704a4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-18 00:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6195a002f9e7384a6d46c578--gamut-preview.netlify.app>https://6195a002f9e7384a6d46c578--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6195a002f9e7384a6d46c578>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-18 00:53 UTC, JoshuaKGoldberg commented
Unsubscribing from the auto-add because I'm on vacation, but let it be known I am _very_ excited to see this in review 😁 👏

2021-11-18 14:27 UTC, dreamwasp reviewed
this looks great + is definitely a huge boost to accessibility, just have a couple of small comments on system props things!

could you link monolith + portal PR envs for these so i could test in the repositories themselves? after i've tested there i'll ✅

2021-11-18 14:27 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +`;
you'll get more reliable css ordering (+ access to system props!) with the [css method from system](https://gamut.codecademy.com/?path=/docs/foundations-system-variants--page)

also wanted to double-check that the background color here should always be gray + not change btwn color modes (@songstephen  🙏)

2021-11-18 14:27 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderListItem/index.tsx
> +`;
same as above, more reliable css ordering + access to breakpoints/system props w/ the css method from system!

2021-11-18 14:27 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/index.tsx
> +`;
you get the idea 😅

2021-11-18 14:27 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/index.tsx
> +    }
this is great!!! i wonder if this behavior could be helpful anywhere else // ported into utility functions to clean up the logic here.

2021-11-18 20:32 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/index.tsx
> +    }
yeah!! i was hoping to move this in to a custom hook someplace down the line

2021-11-18 20:33 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +`;
oh dope!

2021-11-22 23:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.647fee.0<br/>@codecademy/gamut-labs@28.0.12-alpha.647fee.0<br/>@codecademy/gamut@40.3.3-alpha.647fee.0<br/>@codecademy/monaco@0.5.13-alpha.647fee.0<br/>@codecademy/styleguide@50.2.4-alpha.647fee.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-22 23:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619c23a17c4c7d0070786d23--gamut-preview.netlify.app>https://619c23a17c4c7d0070786d23--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619c23a17c4c7d0070786d23>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-22 23:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.19-alpha.1d6548.0<br/>@codecademy/gamut-labs@28.0.14-alpha.1d6548.0<br/>@codecademy/gamut@40.3.4-alpha.1d6548.0<br/>@codecademy/monaco@0.5.14-alpha.1d6548.0<br/>@codecademy/styleguide@50.2.7-alpha.1d6548.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-22 23:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619c25e7336a3e0a9bc60160--gamut-preview.netlify.app>https://619c25e7336a3e0a9bc60160--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619c25e7336a3e0a9bc60160>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-23 20:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.a83fe8.0<br/>@codecademy/gamut-labs@28.1.1-alpha.a83fe8.0<br/>@codecademy/gamut@40.4.2-alpha.a83fe8.0<br/>@codecademy/monaco@0.5.16-alpha.a83fe8.0<br/>@codecademy/styleguide@50.4.1-alpha.a83fe8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-23 20:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619d4e1dc19008007df59d31--gamut-preview.netlify.app>https://619d4e1dc19008007df59d31--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619d4e1dc19008007df59d31>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-24 19:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.728ead.0<br/>@codecademy/gamut-labs@28.1.1-alpha.728ead.0<br/>@codecademy/gamut@40.4.2-alpha.728ead.0<br/>@codecademy/monaco@0.5.16-alpha.728ead.0<br/>@codecademy/styleguide@50.4.1-alpha.728ead.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-24 19:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619e8eb038e1539bf672844d--gamut-preview.netlify.app>https://619e8eb038e1539bf672844d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619e8eb038e1539bf672844d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-24 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.d628b2.0<br/>@codecademy/gamut-labs@28.1.1-alpha.d628b2.0<br/>@codecademy/gamut@40.4.2-alpha.d628b2.0<br/>@codecademy/monaco@0.5.16-alpha.d628b2.0<br/>@codecademy/styleguide@50.4.1-alpha.d628b2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-24 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619e9840b1f5aa6f4ba3fe66--gamut-preview.netlify.app>https://619e9840b1f5aa6f4ba3fe66--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619e9840b1f5aa6f4ba3fe66>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-24 20:48 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.647ab1.0<br/>@codecademy/gamut-labs@28.1.1-alpha.647ab1.0<br/>@codecademy/gamut@40.4.2-alpha.647ab1.0<br/>@codecademy/monaco@0.5.16-alpha.647ab1.0<br/>@codecademy/styleguide@50.4.1-alpha.647ab1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-24 20:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://619ea54a38e153b9647282ed--gamut-preview.netlify.app>https://619ea54a38e153b9647282ed--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/619ea54a38e153b9647282ed>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-29 19:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.60d7fb.0<br/>@codecademy/gamut-labs@28.1.1-alpha.60d7fb.0<br/>@codecademy/gamut@40.4.2-alpha.60d7fb.0<br/>@codecademy/monaco@0.5.16-alpha.60d7fb.0<br/>@codecademy/styleguide@50.4.1-alpha.60d7fb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-29 19:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a52910f72ab96a9ffbe495--gamut-preview.netlify.app>https://61a52910f72ab96a9ffbe495--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a52910f72ab96a9ffbe495>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-29 19:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.037916.0<br/>@codecademy/gamut-labs@28.1.1-alpha.037916.0<br/>@codecademy/gamut@40.4.2-alpha.037916.0<br/>@codecademy/monaco@0.5.16-alpha.037916.0<br/>@codecademy/styleguide@50.4.1-alpha.037916.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-29 19:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a52bb8a8fdcd7873ef0281--gamut-preview.netlify.app>https://61a52bb8a8fdcd7873ef0281--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a52bb8a8fdcd7873ef0281>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-29 22:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.6ed787.0<br/>@codecademy/gamut-labs@28.1.1-alpha.6ed787.0<br/>@codecademy/gamut@40.4.2-alpha.6ed787.0<br/>@codecademy/monaco@0.5.16-alpha.6ed787.0<br/>@codecademy/styleguide@50.4.1-alpha.6ed787.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-29 22:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a55193cf09e619a1256df9--gamut-preview.netlify.app>https://61a55193cf09e619a1256df9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a55193cf09e619a1256df9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-29 22:41 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.88d0de.0<br/>@codecademy/gamut-labs@28.1.1-alpha.88d0de.0<br/>@codecademy/gamut@40.4.2-alpha.88d0de.0<br/>@codecademy/monaco@0.5.16-alpha.88d0de.0<br/>@codecademy/styleguide@50.4.1-alpha.88d0de.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-29 22:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a5578de913a123a26ccf80--gamut-preview.netlify.app>https://61a5578de913a123a26ccf80--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a5578de913a123a26ccf80>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-30 21:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.21-alpha.934e37.0<br/>@codecademy/gamut-labs@28.1.1-alpha.934e37.0<br/>@codecademy/gamut@40.4.2-alpha.934e37.0<br/>@codecademy/monaco@0.5.16-alpha.934e37.0<br/>@codecademy/styleguide@50.4.1-alpha.934e37.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-30 21:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a692600c98bd15d9c08848--gamut-preview.netlify.app>https://61a692600c98bd15d9c08848--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a692600c98bd15d9c08848>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-30 21:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.d1f3ce.0<br/>@codecademy/gamut-labs@28.1.4-alpha.d1f3ce.0<br/>@codecademy/gamut@40.5.3-alpha.d1f3ce.0<br/>@codecademy/monaco@0.5.19-alpha.d1f3ce.0<br/>@codecademy/styleguide@50.4.4-alpha.d1f3ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-30 21:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6944062502d1ce9da1bb8--gamut-preview.netlify.app>https://61a6944062502d1ce9da1bb8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6944062502d1ce9da1bb8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-30 21:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.2018f3.0<br/>@codecademy/gamut-labs@28.1.4-alpha.2018f3.0<br/>@codecademy/gamut@40.5.3-alpha.2018f3.0<br/>@codecademy/monaco@0.5.19-alpha.2018f3.0<br/>@codecademy/styleguide@50.4.4-alpha.2018f3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-30 21:26 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a696f1a4d94b1ca5d0d350--gamut-preview.netlify.app>https://61a696f1a4d94b1ca5d0d350--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a696f1a4d94b1ca5d0d350>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-30 22:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.90e4dc.0<br/>@codecademy/gamut-labs@28.1.4-alpha.90e4dc.0<br/>@codecademy/gamut@40.5.3-alpha.90e4dc.0<br/>@codecademy/monaco@0.5.19-alpha.90e4dc.0<br/>@codecademy/styleguide@50.4.4-alpha.90e4dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-30 22:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a6a856a4d94b2d77d0d20e--gamut-preview.netlify.app>https://61a6a856a4d94b2d77d0d20e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a6a856a4d94b2d77d0d20e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-01 18:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.37351f.0<br/>@codecademy/gamut-labs@28.1.4-alpha.37351f.0<br/>@codecademy/gamut@40.5.3-alpha.37351f.0<br/>@codecademy/monaco@0.5.19-alpha.37351f.0<br/>@codecademy/styleguide@50.4.4-alpha.37351f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-01 18:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a7c43f5e1239693c193cd5--gamut-preview.netlify.app>https://61a7c43f5e1239693c193cd5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a7c43f5e1239693c193cd5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-01 21:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.7e3532.0<br/>@codecademy/gamut-labs@28.1.4-alpha.7e3532.0<br/>@codecademy/gamut@40.5.3-alpha.7e3532.0<br/>@codecademy/monaco@0.5.19-alpha.7e3532.0<br/>@codecademy/styleguide@50.4.4-alpha.7e3532.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-01 21:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a7e43f3c57d38b590f54ee--gamut-preview.netlify.app>https://61a7e43f3c57d38b590f54ee--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a7e43f3c57d38b590f54ee>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-01 21:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.b9072b.0<br/>@codecademy/gamut-labs@28.1.4-alpha.b9072b.0<br/>@codecademy/gamut@40.5.3-alpha.b9072b.0<br/>@codecademy/monaco@0.5.19-alpha.b9072b.0<br/>@codecademy/styleguide@50.4.4-alpha.b9072b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-01 21:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a7ee883c57d39bcd0f528e--gamut-preview.netlify.app>https://61a7ee883c57d39bcd0f528e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a7ee883c57d39bcd0f528e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-02 17:45 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.24-alpha.339160.0<br/>@codecademy/gamut-labs@28.1.4-alpha.339160.0<br/>@codecademy/gamut@40.5.3-alpha.339160.0<br/>@codecademy/monaco@0.5.19-alpha.339160.0<br/>@codecademy/styleguide@50.4.4-alpha.339160.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-02 17:47 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a906b421081456a5044f36--gamut-preview.netlify.app>https://61a906b421081456a5044f36--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a906b421081456a5044f36>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-02 18:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.f849ff.0<br/>@codecademy/gamut-labs@28.2.1-alpha.f849ff.0<br/>@codecademy/gamut@40.5.3-alpha.f849ff.0<br/>@codecademy/monaco@0.5.19-alpha.f849ff.0<br/>@codecademy/styleguide@50.4.5-alpha.f849ff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-02 18:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a90a1ee5e7bb54fbde2c0b--gamut-preview.netlify.app>https://61a90a1ee5e7bb54fbde2c0b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a90a1ee5e7bb54fbde2c0b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-02 18:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.3a5b51.0<br/>@codecademy/gamut-labs@28.2.1-alpha.3a5b51.0<br/>@codecademy/gamut@40.5.3-alpha.3a5b51.0<br/>@codecademy/monaco@0.5.19-alpha.3a5b51.0<br/>@codecademy/styleguide@50.4.5-alpha.3a5b51.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-02 19:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61a917de1f967b66af4b53a1--gamut-preview.netlify.app>https://61a917de1f967b66af4b53a1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61a917de1f967b66af4b53a1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-06 20:18 UTC, JoshuaKGoldberg commented on .eslintrc.js
> +        'react/default-props-match-prop-types': 'off',
Oh yeah if you pull from `main` this should no longer be necessary...

2021-12-06 20:20 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  ]);
Nit: this probably doesn't need a `useMemo`, does it?

2021-12-06 20:49 UTC, JoshuaKGoldberg requested changes
Looks great, thanks again for taking this on!!

Found a bug and that's really the only main blocker. The refactor requests would be nice but if you don't have time I understand 😄

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  typeof window !== 'undefined' ? useLayoutEffect : useEffect;
Nit: you can take this in from `react-use`, we do that elsewhere.

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +      if (isOpen) {
Nit: if statements can be combined. 

I'm sad we don't have a lint rule for this, it'd be pretty easy to detect...

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/index.tsx
> +});
Could you move this to a shared location, since there are too?

Also, if you want, you could use `as const` instead of `Object.freeze` so that TypeScript recognizes the values as literals instead of the general `string` primitives.

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  const [dimensions, setDimensions] = useState({ height: 0, width: 0 });
Suggestion: this component has a lot of hooks-y logic _(aside: can you imagine doing this with class components? yikes)_ that's making it kinda hard to figure out where the areas of logic are. Can they be moved into more isolated, shareable hooks so we can reason about & unit test them on their own?

For example, the dimensions calculations took me a few readthroughs to get that all they're ever used for is `hasDimension` and animation sizing.

```ts
const useDimensions = (listRef: React.RefObject<HTMLElement>) => {
  const [dimensions, setDimensions] = useState({ height: 0, width: 0 });
  const hasDimensions = dimensions.height > 0 && dimensions.width > 0;;

  useIsomorphicLayoutEffect(() => {
    if (listRef.current) {
      const { height, width } = listRef.current.getBoundingClientRect();
      setDimensions({ height, width });
    }
  }, [listRef]);

  return [dimensions, hasDimensions] as const;
}
```

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +      const { height, width } = listRef.current.getBoundingClientRect();
Refactor: have you considered https://github.com/streamich/react-use/blob/master/docs/useMeasure.md to do this instead? Slightly more overhead from the resize observer API, but less code for us & maybe avoiding timing edge cases?

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +  py = { _: 16, md: 8 },
Bug: now the focus outline is very close to the dropdown area around the items, so on the first and last ones you can't easily tell which is focused:

![Screenshot of two items in the Pro Pricing menu with a purple line between them](https://user-images.githubusercontent.com/3335181/144919844-5ed6fd43-f0dc-4796-a5fb-1bc30afbe77c.png)

Production uses different margin/padding so the focus outline is around them:
![Screenshot of two items in the Pro Pricing menu with a purple focus around one](https://user-images.githubusercontent.com/3335181/144919913-4f1f4b26-f67c-41bf-87e5-b636c7f4a9bd.png)

2021-12-06 20:49 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +        )}
Question: Err, who uses an icon? I don't see any on prod. Was that dead code?

2021-12-06 21:14 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +        )}
its for mobile! same element, makes it easier

2021-12-06 21:16 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +  ]);
incredibly fair i feel like originally i had this doing something else lol

2021-12-06 21:29 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +        )}
ahhh there we go ty!

2021-12-06 21:35 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +      const { height, width } = listRef.current.getBoundingClientRect();
the ref that comes from `useMeasure` messes up all of my stuff with focus unfortunately, doesnt return `childNodes` or `children`

2021-12-06 21:35 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +      if (isOpen) {
this was mostly for my own readability

2021-12-06 21:36 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +      if (isOpen) {
Yeah this is very much not a blocker IMO 😄

2021-12-06 21:43 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/index.tsx
> +});
yeah, where should this be moved? i was planning on making a separate ticket to move all of the keyboard nav stuff in to a reusable hook after this merges

2021-12-06 21:54 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/index.tsx
> +});
My default for things only used in one directory is to slap a `utils.tsx` file in there and call it a day. 🤷

2021-12-10 21:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.30-alpha.72f139.0<br/>@codecademy/gamut-labs@28.3.4-alpha.72f139.0<br/>@codecademy/gamut@42.0.1-alpha.72f139.0<br/>@codecademy/monaco@0.5.23-alpha.72f139.0<br/>@codecademy/styleguide@52.0.1-alpha.72f139.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-10 21:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b3c685de7b69b0380620fc--gamut-preview.netlify.app>https://61b3c685de7b69b0380620fc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b3c685de7b69b0380620fc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-14 19:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.9da4ce.0<br/>@codecademy/gamut-labs@28.4.3-alpha.9da4ce.0<br/>@codecademy/gamut@42.1.2-alpha.9da4ce.0<br/>@codecademy/monaco@0.5.25-alpha.9da4ce.0<br/>@codecademy/styleguide@52.2.3-alpha.9da4ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-14 19:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b8ea47f200f7174b71e20d--gamut-preview.netlify.app>https://61b8ea47f200f7174b71e20d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b8ea47f200f7174b71e20d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-14 19:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.7bae5f.0<br/>@codecademy/gamut-labs@28.4.3-alpha.7bae5f.0<br/>@codecademy/gamut@42.1.2-alpha.7bae5f.0<br/>@codecademy/monaco@0.5.25-alpha.7bae5f.0<br/>@codecademy/styleguide@52.2.3-alpha.7bae5f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-14 19:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b8edc955966b10dfcba3d3--gamut-preview.netlify.app>https://61b8edc955966b10dfcba3d3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b8edc955966b10dfcba3d3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-14 19:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.20eeb8.0<br/>@codecademy/gamut-labs@28.4.3-alpha.20eeb8.0<br/>@codecademy/gamut@42.1.2-alpha.20eeb8.0<br/>@codecademy/monaco@0.5.25-alpha.20eeb8.0<br/>@codecademy/styleguide@52.2.3-alpha.20eeb8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-14 19:51 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b8f5c7f93dd11bd7b4adbb--gamut-preview.netlify.app>https://61b8f5c7f93dd11bd7b4adbb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b8f5c7f93dd11bd7b4adbb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-14 21:58 UTC, JoshuaKGoldberg approved these changes
Looks great feels great!

I don't know if you'd consider this bug a blocker or fast follow worthy, so approving 🚀

2021-12-14 21:58 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
> +    <>
Nit: no longer necessary

```suggestion
```

2021-12-14 21:58 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/index.tsx
> +  ]);
Nit: similar comment here, probably doesn't need a memo?

2021-12-14 21:58 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/AppHeader/index.tsx
> +    switch (event.key) {
Sorry, found another bug I think 😅 

Pressing up and down on the keyboard, if the page has scroll, it moves up and down.


https://user-images.githubusercontent.com/3335181/146085871-92a43964-d52d-4ab2-b668-261fe8fcd266.mov

2021-12-15 16:49 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/index.tsx
> +    switch (event.key) {
damn i thought i had fixed that issue!

2021-12-16 15:21 UTC, dreamwasp approved these changes
as i commented before, you'll get more reliable prop ordering with the `css` method from gamut in a few spots, but down to have those completed in a follow-up. this is looking great and nothing blocking from me!

2021-12-16 17:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.34-alpha.ca5302.0<br/>@codecademy/gamut-labs@28.4.3-alpha.ca5302.0<br/>@codecademy/gamut@42.1.2-alpha.ca5302.0<br/>@codecademy/monaco@0.5.25-alpha.ca5302.0<br/>@codecademy/styleguide@52.2.3-alpha.ca5302.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-16 17:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61bb7d04a3d12308b8cacdfe--gamut-preview.netlify.app>https://61bb7d04a3d12308b8cacdfe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61bb7d04a3d12308b8cacdfe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-16 17:58 UTC, thedoomshine commented on packages/gamut-labs/src/AppHeader/index.tsx
> +    switch (event.key) {
fixed!

2021-12-16 18:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.35-alpha.8d532b.0<br/>@codecademy/gamut-labs@28.4.4-alpha.8d532b.0<br/>@codecademy/gamut@42.1.3-alpha.8d532b.0<br/>@codecademy/monaco@0.5.26-alpha.8d532b.0<br/>@codecademy/styleguide@52.2.4-alpha.8d532b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-16 18:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61bb801f3e190d08572a7068--gamut-preview.netlify.app>https://61bb801f3e190d08572a7068--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61bb801f3e190d08572a7068>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-16 18:40 UTC, thedoomshine commented
> as i commented before, you'll get more reliable prop ordering with the `css` method from gamut in a few spots, but down to have those completed in a follow-up. this is looking great and nothing blocking from me!

@dreamwasp i feel like some of my changes got blown away in a rebase, either way just updated everything with `css`!

2021-12-16 19:18 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61bb910b6b71b31dc9c81464--gamut-preview.netlify.app>https://61bb910b6b71b31dc9c81464--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61bb910b6b71b31dc9c81464>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-16 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.35-alpha.168333.0<br/>@codecademy/gamut-labs@28.4.4-alpha.168333.0<br/>@codecademy/gamut@42.1.3-alpha.168333.0<br/>@codecademy/monaco@0.5.26-alpha.168333.0<br/>@codecademy/styleguide@52.2.4-alpha.168333.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-16 19:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61bb94d4111b592002e3801a--gamut-preview.netlify.app>https://61bb94d4111b592002e3801a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61bb94d4111b592002e3801a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-16 19:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.35-alpha.dcb88f.0<br/>@codecademy/gamut-labs@28.4.4-alpha.dcb88f.0<br/>@codecademy/gamut@42.1.3-alpha.dcb88f.0<br/>@codecademy/monaco@0.5.26-alpha.dcb88f.0<br/>@codecademy/styleguide@52.2.4-alpha.dcb88f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-16 19:40 UTC, merged