feat(AppHeaderLinkMobile): show 'new' badge in dropdown header links
Codecademy/gamut pull request #2181
Opened 2021-11-17 17:09 UTC by aionate0812

### Overview

Added `new` badge to dropdown header links. AppHeaderLinkMobile now takes `newBadge` prop. Updated order of resources list in header and footer

### PR Checklist

- [ ] Related to designs:
- [x] Related to JIRA ticket: [Reach-1423](https://codecademy.atlassian.net/browse/REACH-1423)
- [x] I have run this code to verify it works
- [x] This PR includes unit tests for the code change

2021-11-17 17:16 UTC, dreamwasp reviewed
i think maybe this would be more reusable if we just were able to pass an entire `<Badge/>` in (thoughts @songstephen) ? could you also please link the Figma designs?

2021-11-17 17:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.db8ccb.0<br/>@codecademy/gamut-labs@28.0.12-alpha.db8ccb.0<br/>@codecademy/styleguide@50.2.4-alpha.db8ccb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-17 17:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61953982a4685c470c5906fa--gamut-preview.netlify.app>https://61953982a4685c470c5906fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61953982a4685c470c5906fa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-17 17:30 UTC, aionate0812 commented
> could you also please link the Figma designs?

I updated the description

2021-11-17 19:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.17-alpha.4fe795.0<br/>@codecademy/gamut-labs@28.0.12-alpha.4fe795.0<br/>@codecademy/styleguide@50.2.4-alpha.4fe795.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-11-17 19:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61955ad993afa000af3835bc--gamut-preview.netlify.app>https://61955ad993afa000af3835bc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61955ad993afa000af3835bc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-17 20:33 UTC, christian-dinh reviewed
I'm liking this, just one suggestion!

2021-11-17 20:33 UTC, christian-dinh commented on packages/gamut-labs/src/lib/resourcesList/index.ts
> +    hasBadge: false,
I could see us wanting other badges beyond "New" down the line ("Beta" comes to mind). Two ideas I have:
1. change `hasBadge` to `badgeText` (a string) that renders a black badge with the provided text
2. change `hasBadge` to `badge` and just pass a component here (basically move `renderBadge` to this file

the first is easier and the second is more flexible (allows non-text badges, badges with different colors, etc), not sure how likely it is we'll need something other than a plain black badge

2021-11-17 22:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61958931e6e1e826fb7f2292--gamut-preview.netlify.app>https://61958931e6e1e826fb7f2292--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61958931e6e1e826fb7f2292>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-11-22 20:26 UTC, njradford approved these changes
Change look good to me

2021-11-22 20:26 UTC, njradford commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
> +      New
It might be useful to pass in the "New" text here as an argument to `renderBadge`. Though on the other hand, it's easy enough to leave it as is until more badge types are needed.

2021-12-07 18:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.25-alpha.c28da5.0<br/>@codecademy/gamut-labs@28.2.1-alpha.c28da5.0<br/>@codecademy/styleguide@50.4.5-alpha.c28da5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-07 18:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61afa9f98d90813ce355d05a--gamut-preview.netlify.app>https://61afa9f98d90813ce355d05a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61afa9f98d90813ce355d05a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-07 18:52 UTC, aionate0812 commented on packages/gamut-labs/src/lib/resourcesList/index.ts
> +    hasBadge: false,
i applied the suggested changes lmk what you think

2021-12-07 18:53 UTC, christian-dinh approved these changes
oh yeah thanks this is perfect 😗👌

2021-12-09 15:56 UTC, dreamwasp commented on packages/gamut-labs/src/lib/resourcesList/index.tsx
> +
if you update your branch, you should be able to accomplish the same thing just using the [new](https://gamut.codecademy.com/?path=/docs/atoms-badge--badge#size) 'small' size!

2021-12-09 15:56 UTC, dreamwasp requested changes
swap that over + ✨

2021-12-13 17:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.31-alpha.e1983c.0<br/>@codecademy/gamut-labs@28.3.5-alpha.e1983c.0<br/>@codecademy/styleguide@52.1.1-alpha.e1983c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-13 17:05 UTC, dreamwasp approved these changes
🔥

2021-12-13 17:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b77d7c486d3f360e60af11--gamut-preview.netlify.app>https://61b77d7c486d3f360e60af11--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b77d7c486d3f360e60af11>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2021-12-13 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.31-alpha.3ccb25.0<br/>@codecademy/gamut-labs@28.3.5-alpha.3ccb25.0<br/>@codecademy/styleguide@52.1.1-alpha.3ccb25.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2021-12-13 18:54 UTC, merged

2021-12-13 18:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61b797049eda1e113cf880c3--gamut-preview.netlify.app>https://61b797049eda1e113cf880c3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61b797049eda1e113cf880c3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->