fix(GlobalHeader): Accessibility & Tests Fix
Codecademy/gamut pull request #2221
Opened 2022-01-05 19:13 UTC by thedoomshine

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-01-05 19:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.8aac38.0<br/>@codecademy/gamut-kit@0.6.38-alpha.8aac38.0<br/>@codecademy/gamut-labs@28.6.1-alpha.8aac38.0<br/>@codecademy/gamut@42.3.0-alpha.8aac38.0<br/>@codecademy/monaco@0.5.28-alpha.8aac38.0<br/>@codecademy/styleguide@52.5.0-alpha.8aac38.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-05 19:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d5ef8795fdea9fe8711cb2--gamut-preview.netlify.app>https://61d5ef8795fdea9fe8711cb2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d5ef8795fdea9fe8711cb2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-05 19:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.d6f467.0<br/>@codecademy/gamut-kit@0.6.38-alpha.d6f467.0<br/>@codecademy/gamut-labs@28.6.1-alpha.d6f467.0<br/>@codecademy/gamut@42.3.0-alpha.d6f467.0<br/>@codecademy/monaco@0.5.28-alpha.d6f467.0<br/>@codecademy/styleguide@52.5.0-alpha.d6f467.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-05 19:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d5f28b141e31c05d3a1b00--gamut-preview.netlify.app>https://61d5f28b141e31c05d3a1b00--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d5f28b141e31c05d3a1b00>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-06 15:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.7663f7.0<br/>@codecademy/gamut-kit@0.6.38-alpha.7663f7.0<br/>@codecademy/gamut-labs@28.6.1-alpha.7663f7.0<br/>@codecademy/gamut@42.3.0-alpha.7663f7.0<br/>@codecademy/monaco@0.5.28-alpha.7663f7.0<br/>@codecademy/styleguide@52.5.0-alpha.7663f7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-06 15:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d7111e56a6f948ca1bce14--gamut-preview.netlify.app>https://61d7111e56a6f948ca1bce14--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d7111e56a6f948ca1bce14>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-06 16:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.a8bcdb.0<br/>@codecademy/gamut-kit@0.6.38-alpha.a8bcdb.0<br/>@codecademy/gamut-labs@28.6.1-alpha.a8bcdb.0<br/>@codecademy/gamut@42.3.0-alpha.a8bcdb.0<br/>@codecademy/monaco@0.5.28-alpha.a8bcdb.0<br/>@codecademy/styleguide@52.5.0-alpha.a8bcdb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-06 16:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d7167b5b1ce94585ed0674--gamut-preview.netlify.app>https://61d7167b5b1ce94585ed0674--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d7167b5b1ce94585ed0674>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-06 16:37 UTC, JoshuaKGoldberg requested changes
Tested on https://github.com/Codecademy/gamut/pull/2221 and it looks great, thanks!

Just requesting changes on the `ButtonBase` thing as I am scared

2022-01-06 16:37 UTC, JoshuaKGoldberg commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +        type={type ?? 'button'}
Nit: covered in props?

```suggestion
        type={type}
```

2022-01-06 16:37 UTC, JoshuaKGoldberg commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +        as="button"
This scares me. `ButtonBase` is used by a lot of places, including the shared `createButtonComponent`. In theory I agree with the change _(`a` without `href`? blurgh!)_ but we'd have to do a lot of QA to make sure random weird things in the monolith don't break with it. 

Maybe a followup ticket so the hard QA doesn't block this PR? And whatever needs `ButtonBase` in this PR should provide the `as` explicitly?

2022-01-06 16:37 UTC, JoshuaKGoldberg commented on packages/gamut-labs/src/HeaderHeightArea/index.tsx
> +  title?: string;
Question: this is provided in both places. Should it be required?

2022-01-06 17:34 UTC, thedoomshine commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +        type={type ?? 'button'}
we want it to default to `role="button"` only if it doesnt have an `href`, if its a link then role isnt necessary and this lets it be set to `undefined`

2022-01-06 17:35 UTC, thedoomshine commented on packages/gamut-labs/src/HeaderHeightArea/index.tsx
> +  title?: string;
i have no idea tbh, i think that was a @dreamwasp addition

2022-01-06 17:44 UTC, JoshuaKGoldberg commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +        type={type ?? 'button'}
Agreed - and `type = 'button'` above, so `type` is always going to be `string` on line 69.

2022-01-06 17:55 UTC, JoshuaKGoldberg commented on packages/gamut/src/ButtonBase/ButtonBase.tsx
> +        as="button"
Talked on Slack, not a logic change! Yay!

2022-01-06 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@6.1.0-alpha.913aa3.0<br/>@codecademy/gamut-kit@0.6.38-alpha.913aa3.0<br/>@codecademy/gamut-labs@28.6.1-alpha.913aa3.0<br/>@codecademy/gamut@42.3.0-alpha.913aa3.0<br/>@codecademy/monaco@0.5.28-alpha.913aa3.0<br/>@codecademy/styleguide@52.5.0-alpha.913aa3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-06 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61d72dea37b10a5f16ad3943--gamut-preview.netlify.app>https://61d72dea37b10a5f16ad3943--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61d72dea37b10a5f16ad3943>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-06 18:03 UTC, dreamwasp commented on packages/gamut-labs/src/HeaderHeightArea/index.tsx
> +  title?: string;
we can nix this, i think i just seeing what stuck when i added this 😅

2022-01-06 18:06 UTC, JoshuaKGoldberg approved these changes
✨

2022-01-06 19:13 UTC, dreamwasp approved these changes
🙏

2022-01-06 19:14 UTC, merged