fix(LayoutMenu):overflow
Codecademy/gamut pull request #2249
Opened 2022-01-26 18:37 UTC by aionate0812

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-01-26 19:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f19aa02d8d550e2167e04d--gamut-preview.netlify.app>https://61f19aa02d8d550e2167e04d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f19aa02d8d550e2167e04d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-01-27 16:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.47-alpha.563f3a.0<br/>@codecademy/gamut-labs@29.0.2-alpha.563f3a.0<br/>@codecademy/styleguide@54.0.2-alpha.563f3a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-31 15:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.51-alpha.4fccd4.0<br/>@codecademy/gamut-labs@29.2.2-alpha.4fccd4.0<br/>@codecademy/styleguide@54.0.6-alpha.4fccd4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-01-31 15:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61f8028c0a0a9fe964e64676--gamut-preview.netlify.app>https://61f8028c0a0a9fe964e64676--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61f8028c0a0a9fe964e64676>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-02 17:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.51-alpha.c9c07f.0<br/>@codecademy/gamut-labs@29.2.2-alpha.c9c07f.0<br/>@codecademy/styleguide@54.0.6-alpha.c9c07f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-02 17:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fac11b3a1a7c0ab3d690ca--gamut-preview.netlify.app>https://61fac11b3a1a7c0ab3d690ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fac11b3a1a7c0ab3d690ca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-02 19:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fadc20ad7b060fea489aa5--gamut-preview.netlify.app>https://61fadc20ad7b060fea489aa5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fadc20ad7b060fea489aa5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-03 21:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.161ea6.0<br/>@codecademy/gamut-labs@29.2.7-alpha.161ea6.0<br/>@codecademy/styleguide@54.1.2-alpha.161ea6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-03 21:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.0aeb74.0<br/>@codecademy/gamut-labs@29.2.7-alpha.0aeb74.0<br/>@codecademy/styleguide@54.1.2-alpha.0aeb74.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-03 21:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.cdf171.0<br/>@codecademy/gamut-labs@29.2.7-alpha.cdf171.0<br/>@codecademy/styleguide@54.1.2-alpha.cdf171.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-03 21:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fc47ae0504dc1337dbb76a--gamut-preview.netlify.app>https://61fc47ae0504dc1337dbb76a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fc47ae0504dc1337dbb76a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-03 21:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fc47ba15ba081148b9ca9b--gamut-preview.netlify.app>https://61fc47ba15ba081148b9ca9b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fc47ba15ba081148b9ca9b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-03 21:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fc480b85ceea12d5f6b021--gamut-preview.netlify.app>https://61fc480b85ceea12d5f6b021--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fc480b85ceea12d5f6b021>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-03 21:33 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.d74bcf.0<br/>@codecademy/gamut-labs@29.2.7-alpha.d74bcf.0<br/>@codecademy/styleguide@54.1.2-alpha.d74bcf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-03 21:36 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fc4aea09a86812cb8cbc84--gamut-preview.netlify.app>https://61fc4aea09a86812cb8cbc84--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fc4aea09a86812cb8cbc84>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-03 22:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.1e64f0.0<br/>@codecademy/gamut-labs@29.2.7-alpha.1e64f0.0<br/>@codecademy/styleguide@54.1.2-alpha.1e64f0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-03 22:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://61fc532985ceea25b7f6ad2f--gamut-preview.netlify.app>https://61fc532985ceea25b7f6ad2f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/61fc532985ceea25b7f6ad2f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-07 18:03 UTC, njradford approved these changes
Tested in the gamut preview with a long list of nav entries. LGTM 👍

2022-02-15 02:08 UTC, aresnik11 reviewed
Can you add a storybook example of how this would be used? And include a link in the PR description of the corresponding portal app PR

2022-02-15 02:08 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +const Nav = styled.nav(variance.compose(system.layout));
is there a way to limit this to use the layout system props internally but not expose them to the outside as props?

2022-02-15 23:25 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.eadb12.0<br/>@codecademy/gamut-labs@29.2.7-alpha.eadb12.0<br/>@codecademy/styleguide@54.1.2-alpha.eadb12.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-15 23:27 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620c36bf6b11df2af262ef70--gamut-preview.netlify.app>https://620c36bf6b11df2af262ef70--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620c36bf6b11df2af262ef70>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-16 17:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.a05189.0<br/>@codecademy/gamut-labs@29.2.7-alpha.a05189.0<br/>@codecademy/styleguide@54.1.2-alpha.a05189.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-16 19:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.56-alpha.a2ce05.0<br/>@codecademy/gamut-labs@29.2.7-alpha.a2ce05.0<br/>@codecademy/styleguide@54.1.2-alpha.a2ce05.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-16 19:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620d4c5d01bad85f77797ea4--gamut-preview.netlify.app>https://620d4c5d01bad85f77797ea4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620d4c5d01bad85f77797ea4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-16 19:32 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.63-alpha.df726d.0<br/>@codecademy/gamut-labs@29.3.4-alpha.df726d.0<br/>@codecademy/styleguide@54.3.4-alpha.df726d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-16 19:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620d52afc51380673ae4f93d--gamut-preview.netlify.app>https://620d52afc51380673ae4f93d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620d52afc51380673ae4f93d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-17 22:11 UTC, aresnik11 requested changes
There is a ton of extra space in mobile/tablet view in both the story book preview and the preview in the portal app PR (https://github.com/codecademy-engineering/portal-app/pull/1340) that seems to be caused by this new overflow stuff. Thinking since we only need it on desktop we should move where it is getting added

<img width="954" alt="Screen Shot 2022-02-17 at 5 06 18 PM" src="https://user-images.githubusercontent.com/8761638/154579285-08d14c5e-fbf2-4fab-9774-b5f11e73f26c.png">

2022-02-17 22:11 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenu-test.tsx
> +    expect(view.getByTestId('menu')).toHaveStyleRule('overflow-y', 'auto');
i think we can probably do `getByRole('navigation')` here or something along those lines since the html element is `nav`

2022-02-17 22:11 UTC, aresnik11 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +    <Nav menuHeight={menuHeight} data-testid="menu">
looking at this again, don't we only want this height and overflow business on the desktop version? so i think we should move all of this logic to the `Box` that shows on desktop

2022-02-22 22:13 UTC, aionate0812 commented on packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenu-test.tsx
> +    expect(view.getByTestId('menu')).toHaveStyleRule('overflow-y', 'auto');
i moved the `menuHeight` prop to a `Box` inside the nav so i kept `data-testid`

2022-02-22 22:15 UTC, aionate0812 commented on packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
> +    <Nav menuHeight={menuHeight} data-testid="menu">
good call out! - moving the logic to the `Box` also removed the extra space on mobile

2022-02-22 22:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.64-alpha.f60ccd.0<br/>@codecademy/gamut-labs@29.3.5-alpha.f60ccd.0<br/>@codecademy/styleguide@54.3.5-alpha.f60ccd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-22 22:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://621561c074da3e330d4fa909--gamut-preview.netlify.app>https://621561c074da3e330d4fa909--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/621561c074da3e330d4fa909>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-01 15:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.68-alpha.c563b1.0<br/>@codecademy/gamut-labs@29.3.9-alpha.c563b1.0<br/>@codecademy/styleguide@54.3.9-alpha.c563b1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-01 15:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://621e4278990d8e4944cef5ac--gamut-preview.netlify.app>https://621e4278990d8e4944cef5ac--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/621e4278990d8e4944cef5ac>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-08 16:39 UTC, dreamwasp approved these changes
looks great, love the variants here!

2022-03-08 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6227c4ef164a8a0d0fc9d069--gamut-preview.netlify.app>https://6227c4ef164a8a0d0fc9d069--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6227c4ef164a8a0d0fc9d069>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-08 21:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.73-alpha.510fc1.0<br/>@codecademy/gamut-labs@30.1.2-alpha.510fc1.0<br/>@codecademy/styleguide@55.0.5-alpha.510fc1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-08 21:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6227ca62164a8a0ba9c9ea9a--gamut-preview.netlify.app>https://6227ca62164a8a0ba9c9ea9a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6227ca62164a8a0ba9c9ea9a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-08 21:34 UTC, merged