style(Scrollbars): Adding theme colors to global scrollbars
Codecademy/gamut pull request #2266
Opened 2022-02-18 15:59 UTC by thedoomshine

### Overview

Adding theme colors to scrollbars

[Portal App PR](https://github.com/codecademy-engineering/portal-app/pull/1493)
[Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/29547)

### PR Checklist

- [ ] Related to designs:
- [X] Related to JIRA ticket: [WEB-1760](https://codecademy.atlassian.net/browse/WEB-1760?atlOrigin=eyJpIjoiZmY1NDQ4MTQ0M2NlNGIyODlmODYxZWQxMTVjNTdiNmEiLCJwIjoiaiJ9)
- [X] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-02-18 16:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620fc5f4af1dd02c3586372f--gamut-preview.netlify.app>https://620fc5f4af1dd02c3586372f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620fc5f4af1dd02c3586372f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-18 16:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620fcc361404cc00a2759a1a--gamut-preview.netlify.app>https://620fcc361404cc00a2759a1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620fcc361404cc00a2759a1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-18 16:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.4091f8.0<br/>@codecademy/gamut-illustrations@0.22.3-alpha.4091f8.0<br/>@codecademy/gamut-kit@0.6.64-alpha.4091f8.0<br/>@codecademy/gamut-labs@29.3.5-alpha.4091f8.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.4091f8.0<br/>@codecademy/gamut-styles@13.0.3-alpha.4091f8.0<br/>@codecademy/gamut-tests@4.0.3-alpha.4091f8.0<br/>@codecademy/gamut@44.6.2-alpha.4091f8.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.4091f8.0<br/>@codecademy/monaco@0.6.16-alpha.4091f8.0<br/>@codecademy/styleguide@54.3.5-alpha.4091f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-18 16:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://620fcf74601da300758c3cb9--gamut-preview.netlify.app>https://620fcf74601da300758c3cb9--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/620fcf74601da300758c3cb9>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-18 21:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.180762.0<br/>@codecademy/gamut-illustrations@0.22.3-alpha.180762.0<br/>@codecademy/gamut-kit@0.6.64-alpha.180762.0<br/>@codecademy/gamut-labs@29.3.5-alpha.180762.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.180762.0<br/>@codecademy/gamut-styles@13.0.3-alpha.180762.0<br/>@codecademy/gamut-tests@4.0.3-alpha.180762.0<br/>@codecademy/gamut@44.6.2-alpha.180762.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.180762.0<br/>@codecademy/monaco@0.6.16-alpha.180762.0<br/>@codecademy/styleguide@54.3.5-alpha.180762.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-18 21:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62100cebe2b7e00f61f25de6--gamut-preview.netlify.app>https://62100cebe2b7e00f61f25de6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62100cebe2b7e00f61f25de6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-22 15:35 UTC, dreamwasp reviewed
**YES** love this!! could you add links to the monolith + portal alphas so i can test them out there? also tagging @aionate0812 cos we were talking about this work

2022-02-22 18:00 UTC, thedoomshine commented
> **YES** love this!! could you add links to the monolith + portal alphas so i can test them out there? also tagging @aionate0812 cos we were talking about this work

added!

2022-02-22 21:46 UTC, dreamwasp commented on packages/gamut-styles/src/globals/Scrollbars.tsx
> +            ${getColorValue(activeColors['background-primary'])};
i wonder if we want [background-current](https://gamut.codecademy.com/?path=/docs/foundations-colormode--page#current-background) instead of `background-primary` so that the scrollbars match the current background color instead of enforcing beige (@songstephen ?)

like here in articles:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/58054751/155223930-a312fcd2-c278-4d09-ba70-d80c6b5ac8da.png">


also wanna double-check with design cos these background colors will change how certain pages look like the white monolith scrolled-down header with the white background:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/58054751/155224427-0eafabd6-0639-40e5-b746-d208fca117cc.png">

2022-02-23 15:04 UTC, thedoomshine commented on packages/gamut-styles/src/globals/Scrollbars.tsx
> +            ${getColorValue(activeColors['background-primary'])};
`background-current` didnt seem to work in testing, that kept it white in dark mode

2022-02-23 15:55 UTC, dreamwasp commented on packages/gamut-styles/src/globals/Scrollbars.tsx
> +            ${getColorValue(activeColors['background-primary'])};
interesting - i wonder if this has something to do with how we're setting background on certain pages 🤔  i'm gonna play around in the PR envs today + investigate 😎

2022-02-23 16:02 UTC, thedoomshine commented on packages/gamut-styles/src/globals/Scrollbars.tsx
> +            ${getColorValue(activeColors['background-primary'])};
nope, remembered wrong, it turned the background white in light mode and that seemed wrong:
![image](https://user-images.githubusercontent.com/22797790/155357598-a7c3659d-71fc-4b4c-a90b-08c808fdd275.png)

2022-02-23 17:01 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62166848af8b773dc1d91d9a--gamut-preview.netlify.app>https://62166848af8b773dc1d91d9a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62166848af8b773dc1d91d9a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-02-24 22:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.7036ef.0<br/>@codecademy/gamut-illustrations@0.22.3-alpha.7036ef.0<br/>@codecademy/gamut-kit@0.6.65-alpha.7036ef.0<br/>@codecademy/gamut-labs@29.3.6-alpha.7036ef.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.7036ef.0<br/>@codecademy/gamut-styles@13.0.3-alpha.7036ef.0<br/>@codecademy/gamut-tests@4.0.3-alpha.7036ef.0<br/>@codecademy/gamut@44.6.2-alpha.7036ef.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.7036ef.0<br/>@codecademy/monaco@0.6.16-alpha.7036ef.0<br/>@codecademy/styleguide@54.3.6-alpha.7036ef.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-02-24 22:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62180149546572008bf4d32c--gamut-preview.netlify.app>https://62180149546572008bf4d32c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62180149546572008bf4d32c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-07 16:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.44a27d.0<br/>@codecademy/gamut-illustrations@0.22.3-alpha.44a27d.0<br/>@codecademy/gamut-kit@0.6.69-alpha.44a27d.0<br/>@codecademy/gamut-labs@30.0.1-alpha.44a27d.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.44a27d.0<br/>@codecademy/gamut-styles@13.0.3-alpha.44a27d.0<br/>@codecademy/gamut-tests@4.0.3-alpha.44a27d.0<br/>@codecademy/gamut@45.0.1-alpha.44a27d.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.44a27d.0<br/>@codecademy/monaco@0.6.19-alpha.44a27d.0<br/>@codecademy/styleguide@55.0.1-alpha.44a27d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-07 16:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62262e07d311f600bcb74339--gamut-preview.netlify.app>https://62262e07d311f600bcb74339--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62262e07d311f600bcb74339>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-07 19:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.2b82d6.0<br/>@codecademy/gamut-illustrations@0.22.3-alpha.2b82d6.0<br/>@codecademy/gamut-kit@0.6.70-alpha.2b82d6.0<br/>@codecademy/gamut-labs@30.0.2-alpha.2b82d6.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.2b82d6.0<br/>@codecademy/gamut-styles@13.0.3-alpha.2b82d6.0<br/>@codecademy/gamut-tests@4.0.3-alpha.2b82d6.0<br/>@codecademy/gamut@45.0.1-alpha.2b82d6.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.2b82d6.0<br/>@codecademy/monaco@0.6.19-alpha.2b82d6.0<br/>@codecademy/styleguide@55.0.2-alpha.2b82d6.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-09 19:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.04d1bd.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.04d1bd.0<br/>@codecademy/gamut-kit@0.6.75-alpha.04d1bd.0<br/>@codecademy/gamut-labs@30.2.1-alpha.04d1bd.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.04d1bd.0<br/>@codecademy/gamut-styles@13.0.3-alpha.04d1bd.0<br/>@codecademy/gamut-tests@4.0.3-alpha.04d1bd.0<br/>@codecademy/gamut@45.0.3-alpha.04d1bd.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.04d1bd.0<br/>@codecademy/monaco@0.6.21-alpha.04d1bd.0<br/>@codecademy/styleguide@55.1.1-alpha.04d1bd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-09 19:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6228fe4942f988417a19f725--gamut-preview.netlify.app>https://6228fe4942f988417a19f725--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6228fe4942f988417a19f725>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-10 16:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.1.2-alpha.c65f95.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.c65f95.0<br/>@codecademy/gamut-kit@0.6.77-alpha.c65f95.0<br/>@codecademy/gamut-labs@30.2.3-alpha.c65f95.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.c65f95.0<br/>@codecademy/gamut-styles@13.0.3-alpha.c65f95.0<br/>@codecademy/gamut-tests@4.0.3-alpha.c65f95.0<br/>@codecademy/gamut@45.1.2-alpha.c65f95.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.c65f95.0<br/>@codecademy/monaco@0.6.23-alpha.c65f95.0<br/>@codecademy/styleguide@55.1.3-alpha.c65f95.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-11 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.786535.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.786535.0<br/>@codecademy/gamut-kit@0.6.79-alpha.786535.0<br/>@codecademy/gamut-labs@30.2.5-alpha.786535.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.786535.0<br/>@codecademy/gamut-styles@13.0.3-alpha.786535.0<br/>@codecademy/gamut-tests@4.0.3-alpha.786535.0<br/>@codecademy/gamut@45.1.4-alpha.786535.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.786535.0<br/>@codecademy/monaco@0.6.25-alpha.786535.0<br/>@codecademy/styleguide@55.1.5-alpha.786535.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-11 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622ba8a23cb123373a195817--gamut-preview.netlify.app>https://622ba8a23cb123373a195817--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622ba8a23cb123373a195817>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-14 18:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.acc04c.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.acc04c.0<br/>@codecademy/gamut-kit@0.6.79-alpha.acc04c.0<br/>@codecademy/gamut-labs@30.2.5-alpha.acc04c.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.acc04c.0<br/>@codecademy/gamut-styles@13.0.3-alpha.acc04c.0<br/>@codecademy/gamut-tests@4.0.3-alpha.acc04c.0<br/>@codecademy/gamut@45.1.4-alpha.acc04c.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.acc04c.0<br/>@codecademy/monaco@0.6.25-alpha.acc04c.0<br/>@codecademy/styleguide@55.1.5-alpha.acc04c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-14 18:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622f8c32374a95407bd95330--gamut-preview.netlify.app>https://622f8c32374a95407bd95330--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622f8c32374a95407bd95330>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-14 19:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.0f84f5.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.0f84f5.0<br/>@codecademy/gamut-kit@0.6.79-alpha.0f84f5.0<br/>@codecademy/gamut-labs@30.2.5-alpha.0f84f5.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.0f84f5.0<br/>@codecademy/gamut-styles@13.0.3-alpha.0f84f5.0<br/>@codecademy/gamut-tests@4.0.3-alpha.0f84f5.0<br/>@codecademy/gamut@45.1.4-alpha.0f84f5.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.0f84f5.0<br/>@codecademy/monaco@0.6.25-alpha.0f84f5.0<br/>@codecademy/styleguide@55.1.5-alpha.0f84f5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-14 21:11 UTC, jakemhiller commented on packages/gamut-styles/src/ColorMode.tsx
> +        <Scrollbars />
is this necessary, when we're adding the styles manually above?

2022-03-15 16:59 UTC, thedoomshine commented on packages/gamut-styles/src/ColorMode.tsx
> +        <Scrollbars />
yes, the scrollbars element is what adds it to `html, body`, `scrollbarStyles` adds it to the scrolling container. more for the future changes than anything

2022-03-15 17:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.7131e9.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.7131e9.0<br/>@codecademy/gamut-kit@0.6.80-alpha.7131e9.0<br/>@codecademy/gamut-labs@30.2.6-alpha.7131e9.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.7131e9.0<br/>@codecademy/gamut-styles@13.0.3-alpha.7131e9.0<br/>@codecademy/gamut-tests@4.0.3-alpha.7131e9.0<br/>@codecademy/gamut@45.2.1-alpha.7131e9.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.7131e9.0<br/>@codecademy/monaco@0.6.26-alpha.7131e9.0<br/>@codecademy/styleguide@55.1.6-alpha.7131e9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-15 17:33 UTC, jakemhiller commented on packages/gamut-styles/src/ColorMode.tsx
> +        <Scrollbars />
I would think you could add the `<Scrollbars/>` component in the same place we add `<Reboot />` and leave it off of `ColorMode` (keeping the styles)?

2022-03-15 18:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.275660.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.275660.0<br/>@codecademy/gamut-kit@0.6.80-alpha.275660.0<br/>@codecademy/gamut-labs@30.2.6-alpha.275660.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.275660.0<br/>@codecademy/gamut-styles@13.0.3-alpha.275660.0<br/>@codecademy/gamut-tests@4.0.3-alpha.275660.0<br/>@codecademy/gamut@45.2.1-alpha.275660.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.275660.0<br/>@codecademy/monaco@0.6.26-alpha.275660.0<br/>@codecademy/styleguide@55.1.6-alpha.275660.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-15 19:00 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6230e24627ca0015a0fc944b--gamut-preview.netlify.app>https://6230e24627ca0015a0fc944b--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6230e24627ca0015a0fc944b>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-16 14:07 UTC, thedoomshine commented on packages/gamut-styles/src/ColorMode.tsx
> +        <Scrollbars />
tried that before, need `Scrollbars` on `ColorMode` so i have access to the theme

2022-03-16 14:27 UTC, dreamwasp commented on packages/gamut-styles/src/ColorMode.tsx
> +        {isGlobal && <Scrollbars />}
whats `isGlobal` for? just a prop that decides if the scrollbars need to be injected?

2022-03-16 14:50 UTC, thedoomshine commented on packages/gamut-styles/src/ColorMode.tsx
> +        {isGlobal && <Scrollbars />}
its setting up for a future change, in the future we need a check to see if any given `Background` component is the highest in the dom, and then pass that variable to this element which changes the scrollbar color for `html, body` instead of just the locally scoped component

worked through it in this thread yesterday: https://codecademy.slack.com/archives/C02CPQFEFGV/p1647285801715999

2022-03-16 15:36 UTC, dreamwasp reviewed
i tooled around in portal + monlith and only saw a weirdness on the homepage (as i noted on that PR). feel a little out of my depth here so will let @jakemhiller approve but lgtm!!

2022-03-16 15:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.e4a9fd.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.e4a9fd.0<br/>@codecademy/gamut-kit@0.6.81-alpha.e4a9fd.0<br/>@codecademy/gamut-labs@30.2.7-alpha.e4a9fd.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.e4a9fd.0<br/>@codecademy/gamut-styles@13.0.3-alpha.e4a9fd.0<br/>@codecademy/gamut-tests@4.0.3-alpha.e4a9fd.0<br/>@codecademy/gamut@45.2.2-alpha.e4a9fd.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.e4a9fd.0<br/>@codecademy/monaco@0.6.27-alpha.e4a9fd.0<br/>@codecademy/styleguide@55.1.7-alpha.e4a9fd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-16 15:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://623208105395ca2986d83b38--gamut-preview.netlify.app>https://623208105395ca2986d83b38--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/623208105395ca2986d83b38>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-16 16:03 UTC, jakemhiller commented on packages/gamut-styles/src/ColorMode.tsx
> +        {isGlobal && <Scrollbars />}
not 100% sure this will work, since the "root" css variables still wouldn't change. But i'm ok with stubbing it out as long as nested scrollbars are still styled correctly by the `scrollbarStyles`

2022-03-16 17:01 UTC, jakemhiller requested changes
I think we need a Storybook page with this showing how it works with nested ColorModes before this can ship

2022-03-18 20:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.38607e.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.38607e.0<br/>@codecademy/gamut-kit@0.6.82-alpha.38607e.0<br/>@codecademy/gamut-labs@30.3.1-alpha.38607e.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.38607e.0<br/>@codecademy/gamut-styles@13.0.3-alpha.38607e.0<br/>@codecademy/gamut-tests@4.0.3-alpha.38607e.0<br/>@codecademy/gamut@45.2.2-alpha.38607e.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.38607e.0<br/>@codecademy/monaco@0.6.27-alpha.38607e.0<br/>@codecademy/styleguide@55.2.1-alpha.38607e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-18 20:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6234e6a64244cd0094e2aea8--gamut-preview.netlify.app>https://6234e6a64244cd0094e2aea8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6234e6a64244cd0094e2aea8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-21 16:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.2ef005.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.2ef005.0<br/>@codecademy/gamut-kit@0.6.83-alpha.2ef005.0<br/>@codecademy/gamut-labs@30.3.2-alpha.2ef005.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.2ef005.0<br/>@codecademy/gamut-styles@13.0.3-alpha.2ef005.0<br/>@codecademy/gamut-tests@4.0.3-alpha.2ef005.0<br/>@codecademy/gamut@45.2.2-alpha.2ef005.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.2ef005.0<br/>@codecademy/monaco@0.6.27-alpha.2ef005.0<br/>@codecademy/styleguide@55.2.2-alpha.2ef005.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-21 16:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6238a84281e6d2099fb8e3c5--gamut-preview.netlify.app>https://6238a84281e6d2099fb8e3c5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6238a84281e6d2099fb8e3c5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-21 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.ad1afa.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.ad1afa.0<br/>@codecademy/gamut-kit@0.6.83-alpha.ad1afa.0<br/>@codecademy/gamut-labs@30.3.2-alpha.ad1afa.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.ad1afa.0<br/>@codecademy/gamut-styles@13.0.3-alpha.ad1afa.0<br/>@codecademy/gamut-tests@4.0.3-alpha.ad1afa.0<br/>@codecademy/gamut@45.2.2-alpha.ad1afa.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.ad1afa.0<br/>@codecademy/monaco@0.6.27-alpha.ad1afa.0<br/>@codecademy/styleguide@55.2.2-alpha.ad1afa.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-21 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6238d7a6a41c0d00a04f9eb6--gamut-preview.netlify.app>https://6238d7a6a41c0d00a04f9eb6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6238d7a6a41c0d00a04f9eb6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-21 20:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.51123c.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.51123c.0<br/>@codecademy/gamut-kit@0.6.83-alpha.51123c.0<br/>@codecademy/gamut-labs@30.3.2-alpha.51123c.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.51123c.0<br/>@codecademy/gamut-styles@13.0.3-alpha.51123c.0<br/>@codecademy/gamut-tests@4.0.3-alpha.51123c.0<br/>@codecademy/gamut@45.2.2-alpha.51123c.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.51123c.0<br/>@codecademy/monaco@0.6.27-alpha.51123c.0<br/>@codecademy/styleguide@55.2.2-alpha.51123c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-21 20:43 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6238e36616023a0b06e31e36--gamut-preview.netlify.app>https://6238e36616023a0b06e31e36--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6238e36616023a0b06e31e36>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-21 20:53 UTC, jakemhiller commented on packages/gamut-styles/src/globals/Reboot.tsx
> +    overflow: hidden;
is this still needed? it seems like it breaks scrolling on the colormode page. https://6238e36616023a0b06e31e36--gamut-preview.netlify.app/?path=/docs/foundations-colormode--page

2022-03-21 20:54 UTC, thedoomshine commented on packages/gamut-styles/src/globals/Reboot.tsx
> +    overflow: hidden;
yeah this is the only way it works, lemme check it out

2022-03-21 20:59 UTC, thedoomshine commented on packages/gamut-styles/src/globals/Reboot.tsx
> +    overflow: hidden;
fixed!

2022-03-21 21:04 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-icons@7.2.1-alpha.392c9d.0<br/>@codecademy/gamut-illustrations@0.24.1-alpha.392c9d.0<br/>@codecademy/gamut-kit@0.6.83-alpha.392c9d.0<br/>@codecademy/gamut-labs@30.3.2-alpha.392c9d.0<br/>@codecademy/gamut-patterns@0.8.4-alpha.392c9d.0<br/>@codecademy/gamut-styles@13.0.3-alpha.392c9d.0<br/>@codecademy/gamut-tests@4.0.3-alpha.392c9d.0<br/>@codecademy/gamut@45.2.2-alpha.392c9d.0<br/>@codecademy/markdown-overrides@0.8.3-alpha.392c9d.0<br/>@codecademy/monaco@0.6.27-alpha.392c9d.0<br/>@codecademy/styleguide@55.2.2-alpha.392c9d.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-21 21:06 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6238e8b03ec020205f7fe9c1--gamut-preview.netlify.app>https://6238e8b03ec020205f7fe9c1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6238e8b03ec020205f7fe9c1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-29 16:43 UTC, thedoomshine commented on packages/gamut-labs/src/GlobalPage/index.tsx
> +    overflow: `auto`,
in weeks i havent been able to find a more elegant solution than this, if we cant get this through then i think we need to table scrollbars indefinitely, every other solution would require far more code and be just as breaking a change but on a much larger scale

2023-05-22 23:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/gamut?pullRequest=2266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/gamut?pullRequest=2266) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: thedoomshine<br/>:x: Morgan Blackhurst<br/><hr/>**Morgan Blackhurst** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/gamut?pullRequest=2266) it.</sub>

2023-07-05 13:50 UTC, closed without merging