make svg image height 100%
Codecademy/gamut pull request #2283
Opened 2022-03-14 20:15 UTC by vonbarown

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-03-14 20:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.79-alpha.55a212.0<br/>@codecademy/gamut-labs@30.2.5-alpha.55a212.0<br/>@codecademy/styleguide@55.1.5-alpha.55a212.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-14 20:22 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622fa3e1f920c800b5d0ccd0--gamut-preview.netlify.app>https://622fa3e1f920c800b5d0ccd0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622fa3e1f920c800b5d0ccd0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-14 21:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.79-alpha.8c3842.0<br/>@codecademy/gamut-labs@30.2.5-alpha.8c3842.0<br/>@codecademy/styleguide@55.1.5-alpha.8c3842.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-14 21:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://622fb0323da6a41594c6b117--gamut-preview.netlify.app>https://622fb0323da6a41594c6b117--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/622fb0323da6a41594c6b117>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-15 13:54 UTC, dreamwasp requested changes

2022-03-15 13:54 UTC, dreamwasp commented on packages/gamut-labs/src/PausableImage/index.tsx
> +      heigh: '100%',
```suggestion
      height: '100%',
```

2022-03-15 13:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.79-alpha.873183.0<br/>@codecademy/gamut-labs@30.2.5-alpha.873183.0<br/>@codecademy/gamut@45.2.0-alpha.873183.0<br/>@codecademy/monaco@0.6.25-alpha.873183.0<br/>@codecademy/styleguide@55.1.5-alpha.873183.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-03-15 13:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62309bcfde67ff183840c987--gamut-preview.netlify.app>https://62309bcfde67ff183840c987--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62309bcfde67ff183840c987>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-03-15 14:00 UTC, vonbarown commented on packages/gamut-labs/src/PausableImage/index.tsx
> +      heigh: '100%',
thanks for catching, the issue doesn't appear to be from the gamut component but from the container on the monolith. have a fix in this [PR](https://github.com/codecademy-engineering/Codecademy/pull/29919).

2022-03-15 16:07 UTC, closed without merging