feat(HorizontalScrollBar): added Horizontal Scrollbar component
Codecademy/gamut pull request #2304
Opened 2022-04-01 16:10 UTC by cstatro

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-04-01 17:16 UTC, cstatro commented on packages/gamut/src/HorizontalScrollBar/index.tsx
> +        rootMargin: '100% 0% 100% 0%',
setting the root margin here, we're making sure that intersection state changes on our entry only apply horizontally.

2022-04-01 17:19 UTC, cstatro commented on packages/gamut/src/HorizontalScrollBar/index.tsx
> +              data-observerindex={index}
`entries` being iterated on in our observer are elements that are changing intersection state so the we can't use the index of the entries array to determine if an element is first or last in an array of children. To make this logic possible I've added `data` property here so in our callback we can determine what array index our element is.

2022-04-01 17:25 UTC, cstatro commented on packages/gamut/src/HorizontalScrollBar/index.tsx
> +    if (typeof window === 'undefined') return null;
I did this to prevent `SSR` errors I was getting when QAing but if there's a better way please let me know 😅

2022-04-01 17:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.d25214.0<br/>@codecademy/gamut-labs@30.4.1-alpha.d25214.0<br/>@codecademy/gamut@45.2.2-alpha.d25214.0<br/>@codecademy/monaco@0.6.27-alpha.d25214.0<br/>@codecademy/styleguide@55.2.3-alpha.d25214.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-01 17:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.fa3a6e.0<br/>@codecademy/gamut-labs@30.4.1-alpha.fa3a6e.0<br/>@codecademy/gamut@45.2.2-alpha.fa3a6e.0<br/>@codecademy/monaco@0.6.27-alpha.fa3a6e.0<br/>@codecademy/styleguide@55.2.3-alpha.fa3a6e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-01 17:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62473bf915527d5f9767f514--gamut-preview.netlify.app>https://62473bf915527d5f9767f514--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62473bf915527d5f9767f514>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-01 18:11 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.e3b862.0<br/>@codecademy/gamut-labs@30.4.1-alpha.e3b862.0<br/>@codecademy/gamut@45.2.2-alpha.e3b862.0<br/>@codecademy/monaco@0.6.27-alpha.e3b862.0<br/>@codecademy/styleguide@55.2.3-alpha.e3b862.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-01 18:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624740b3ac4eaa75ee8b3580--gamut-preview.netlify.app>https://624740b3ac4eaa75ee8b3580--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624740b3ac4eaa75ee8b3580>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-05 13:26 UTC, dreamwasp approved these changes
this is nifty but i'm a little confused by the behavior. on voiceover one of the two buttons pop up and skip me to the beginning or end, but there's no focus management and navigating back to the content is awkward. i also think its a little awkward how only one of the two arrows appears when you're in the middle of the cards content (if i'm centered in the content, i would probably like to have the option to jump forward or back)

tagging expertz @songstephen + @katiezutter here to to get their two cents~

2022-04-05 13:26 UTC, dreamwasp commented on packages/gamut/src/HorizontalScrollBar/index.tsx
> +
can we use the css method on any of these?

2022-04-05 13:27 UTC, dreamwasp requested changes
meant to comment, not approve, oops

2022-04-05 20:54 UTC, cstatro commented on packages/gamut/src/HorizontalScrollBar/index.tsx
> +
moved the overflow rule into css method, I think it reads better to have the opacity rules next to each other rather than splitting up the psuedo selected rule and default rule.

2022-04-05 20:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.728823.0<br/>@codecademy/gamut-labs@30.4.1-alpha.728823.0<br/>@codecademy/gamut@45.2.2-alpha.728823.0<br/>@codecademy/monaco@0.6.27-alpha.728823.0<br/>@codecademy/styleguide@55.2.3-alpha.728823.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-05 20:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624cadb44c08e000af1d5c78--gamut-preview.netlify.app>https://624cadb44c08e000af1d5c78--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624cadb44c08e000af1d5c78>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-06 00:13 UTC, jakemhiller commented on packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
> +  "HorizontalScrollBar",
Not sure about the naming, since it's not really acting as a scrollbar, it's mostly about scrolling through arbitrary content. Maybe `HorizontalScrollMenu` or something?

2022-04-06 15:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.16b5ea.0<br/>@codecademy/gamut-labs@30.4.1-alpha.16b5ea.0<br/>@codecademy/gamut@45.2.2-alpha.16b5ea.0<br/>@codecademy/monaco@0.6.27-alpha.16b5ea.0<br/>@codecademy/styleguide@55.2.3-alpha.16b5ea.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 15:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624db218c7c0244b60328652--gamut-preview.netlify.app>https://624db218c7c0244b60328652--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624db218c7c0244b60328652>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 21:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.84-alpha.9a70f8.0<br/>@codecademy/gamut-labs@30.4.1-alpha.9a70f8.0<br/>@codecademy/gamut@45.2.2-alpha.9a70f8.0<br/>@codecademy/monaco@0.6.27-alpha.9a70f8.0<br/>@codecademy/styleguide@55.2.3-alpha.9a70f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-07 21:04 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624f51d43ea06d53e9899511--gamut-preview.netlify.app>https://624f51d43ea06d53e9899511--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624f51d43ea06d53e9899511>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-11 14:25 UTC, dreamwasp reviewed
is looking way better - could you put it up in monolith PR so i can take a look there? then will ✅

2022-04-11 14:25 UTC, dreamwasp commented on packages/styleguide/stories/Molecules/HorizontalScrollMenu/index.stories.mdx
> +import { HorizontalScrollMenu } from '@codecademy/gamut';
can you move this to -labs?

2022-04-11 21:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.0867d3.0<br/>@codecademy/gamut-labs@31.3.4-alpha.0867d3.0<br/>@codecademy/gamut@46.1.1-alpha.0867d3.0<br/>@codecademy/monaco@0.6.33-alpha.0867d3.0<br/>@codecademy/styleguide@56.2.4-alpha.0867d3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-11 21:30 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62549de31445ad1ff66b4d7a--gamut-preview.netlify.app>https://62549de31445ad1ff66b4d7a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62549de31445ad1ff66b4d7a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-11 23:07 UTC, cstatro commented
@dreamwasp https://pr-30344-monolith.dev-eks.codecademy.com/  put together an implementation on the catalog cards on homepage
![image](https://user-images.githubusercontent.com/45748761/162847388-a56778f5-b7d6-4c7f-b9df-3728e0f3bacb.png)

2022-04-12 20:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.7beef3.0<br/>@codecademy/gamut-labs@31.3.4-alpha.7beef3.0<br/>@codecademy/styleguide@56.2.4-alpha.7beef3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-12 20:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6255db66d2ef75132c10b186--gamut-preview.netlify.app>https://6255db66d2ef75132c10b186--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6255db66d2ef75132c10b186>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-12 21:01 UTC, dreamwasp approved these changes

2022-04-12 21:44 UTC, merged