(WIP) feat(AppHeaderCatalogDropdown): added AppHeaderCatalogDropdown component
Codecademy/gamut pull request #2311
Opened 2022-04-06 15:06 UTC by zippyzow

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change

2022-04-06 17:02 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.1178dd.0<br/>@codecademy/gamut-labs@31.3.4-alpha.1178dd.0<br/>@codecademy/styleguide@56.2.4-alpha.1178dd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 17:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624dc82f6d782b00c28bfe80--gamut-preview.netlify.app>https://624dc82f6d782b00c28bfe80--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624dc82f6d782b00c28bfe80>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-06 17:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.09db70.0<br/>@codecademy/gamut-labs@31.3.4-alpha.09db70.0<br/>@codecademy/styleguide@56.2.4-alpha.09db70.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 17:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624dd40470e0820e1e06010f--gamut-preview.netlify.app>https://624dd40470e0820e1e06010f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624dd40470e0820e1e06010f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-06 18:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.8808d8.0<br/>@codecademy/gamut-labs@31.3.4-alpha.8808d8.0<br/>@codecademy/styleguide@56.2.4-alpha.8808d8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 18:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624dda13d016f50094c8aa94--gamut-preview.netlify.app>https://624dda13d016f50094c8aa94--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624dda13d016f50094c8aa94>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-06 21:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.b112ba.0<br/>@codecademy/gamut-labs@31.3.4-alpha.b112ba.0<br/>@codecademy/styleguide@56.2.4-alpha.b112ba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 21:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624e04212cc9c60abb35c83f--gamut-preview.netlify.app>https://624e04212cc9c60abb35c83f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624e04212cc9c60abb35c83f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-06 22:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.4657b8.0<br/>@codecademy/gamut-labs@31.3.4-alpha.4657b8.0<br/>@codecademy/styleguide@56.2.4-alpha.4657b8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-06 22:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624e142677f85211d8bae7b6--gamut-preview.netlify.app>https://624e142677f85211d8bae7b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624e142677f85211d8bae7b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 01:34 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624e3f92b62e7a00b3a19b64--gamut-preview.netlify.app>https://624e3f92b62e7a00b3a19b64--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624e3f92b62e7a00b3a19b64>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 01:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.dc85ae.0<br/>@codecademy/gamut-labs@31.3.4-alpha.dc85ae.0<br/>@codecademy/styleguide@56.2.4-alpha.dc85ae.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-07 01:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624e43ba19cd0802278adfc2--gamut-preview.netlify.app>https://624e43ba19cd0802278adfc2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624e43ba19cd0802278adfc2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 02:42 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> -const DropdownAnchor = styled(Anchor)(
Since I am utilizing these components for AppHeadCatalogDropdown, I moved them to the [shared folder below. ](packages/gamut-labs/src/AppHeader/shared.tsx)

2022-04-07 02:44 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
Since I am utilizing these components for `AppHeaderCatalogDropdown`, I moved them to the [shared folder below. ](https://github.com/Codecademy/gamut/pull/2311/files#diff-31e505c6c12bd1da9447bda374dc558780889ce1940c28a88120d94b7799473bR6-R90)

2022-04-07 02:45 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> -
Since I am utilizing these components for `AppHeaderCatalogDropdown`, I moved them to the [shared folder below. ](https://github.com/Codecademy/gamut/pull/2311/files#diff-31e505c6c12bd1da9447bda374dc558780889ce1940c28a88120d94b7799473bR6-R90)

2022-04-07 02:45 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
> +} from '../../shared';
Since I am utilizing these components for `AppHeaderCatalogDropdown`, I moved them to the [shared folder below. ](https://github.com/Codecademy/gamut/pull/2311/files#diff-31e505c6c12bd1da9447bda374dc558780889ce1940c28a88120d94b7799473bR6-R90)

2022-04-07 14:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.4a75bf.0<br/>@codecademy/gamut-labs@31.3.4-alpha.4a75bf.0<br/>@codecademy/styleguide@56.2.4-alpha.4a75bf.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-07 14:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624eefb1c27b8f00614986c2--gamut-preview.netlify.app>https://624eefb1c27b8f00614986c2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624eefb1c27b8f00614986c2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 16:09 UTC, borisonr reviewed
this is looking really great! leaving a few small Qs

2022-04-07 16:09 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
> +  useEffect(() => {
would it be possible to use the AppHeaderDropdown and extend that to allow for non-text children so that we don't have to copy paste the same logic?

2022-04-07 16:09 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledTitle = styled(Text)`
how come we can't add these styles as in-line props on Text? if the designs are not using our normal Text sizes/numbers we should push back against design on why

2022-04-07 16:09 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +                section.title !== 'Popular courses' ? '7rem' : '8rem'
i wonder if there's a less brittle way to do this so it doesn't break if we change the text? like write a helper method to check if it contains subheaders in the object?

2022-04-07 16:09 UTC, borisonr commented on packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
> -
can you make a note to specifically add this test back in in the ticket? seems like we just need to be more specific with where we're looking for projects and challenges

2022-04-07 18:01 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
> +  const [height, setHeight] = useState(0);
100% has it cut off, but fit-content works just as effectively as how I'm doing now, so i can make this change.

2022-04-07 18:16 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
> +  useEffect(() => {
I was trying not to pollute the `AppHeaderDropdown` with conditionals and keep that separate since this is experimental but i can try to refactor to see how this looks.

2022-04-07 18:16 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledTitle = styled(Text)`
Yes, the font-sizes in the designs arent our normal numbers. Mark also commented font looks small. I can ask Tamar (or Brendan since she is back Wed)?

2022-04-07 18:16 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +                section.title !== 'Popular courses' ? '7rem' : '8rem'
Good idea, I can do this.

2022-04-07 18:22 UTC, zippyzow commented on packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
> -
I think the specificity in your resourcesList tests seem more fitting for these tests. They can specifically check the content that is being fed to the component whereas this GlobalHeader tests feels more broad (checking the menu names vs the content inside). What do you think?

2022-04-07 18:47 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
> +  useEffect(() => {
i'd be curious to hear @thedoomshine's thoughts too since she worked on the header recently
maybe we could at least factor out shared hooks or something?

2022-04-07 18:48 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledTitle = styled(Text)`
yeah why dont you see if you can get brendan to help out while tamar is out

2022-04-07 20:13 UTC, borisonr commented on packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
> -
oh interesting so you're saying we can just delete this, that works for me!

2022-04-07 20:35 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.5e62ff.0<br/>@codecademy/gamut-labs@31.3.4-alpha.5e62ff.0<br/>@codecademy/styleguide@56.2.4-alpha.5e62ff.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-07 20:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624f4bb93afaed08b425d937--gamut-preview.netlify.app>https://624f4bb93afaed08b425d937--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624f4bb93afaed08b425d937>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-07 21:50 UTC, zippyzow commented on packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
> -
yeah, ill add a note in the ticket

2022-04-07 22:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.278839.0<br/>@codecademy/gamut-labs@31.3.4-alpha.278839.0<br/>@codecademy/styleguide@56.2.4-alpha.278839.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-07 22:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://624f5fb2de434805276e1811--gamut-preview.netlify.app>https://624f5fb2de434805276e1811--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/624f5fb2de434805276e1811>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-08 16:10 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledTitle = styled(Text)`
Brendan said:

> Hi Hailey, thanks for flagging this. It does look a bit small to me— I might try running both of the left-hand side type styles at 12 for now, to avoid dropping down to that 11pt size. I’ve adjusted a mock on the Figma page and commented you on it.
> I’ll also ask Stephen to take a look from the Design System perspective

2022-04-11 14:22 UTC, dreamwasp reviewed
this all looks good to me,  just a couple small things. will let @thedoomshine give the final ✅

2022-04-11 14:22 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  color: ${theme.colors['navy-500']};
the rest of the header is works with ColorMode, can we swap this to a [semantically named ColorMode color](https://gamut.codecademy.com/?path=/docs/foundations-colormode--page)?

2022-04-11 14:22 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledLinkAnchor = styled(Anchor)`
can we swap all of the styled components in this file over to using [the css method](https://gamut.codecademy.com/?path=/docs/foundations-system-variants--page)?

2022-04-11 14:22 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
> +          className={cx(isOpen && 'open')}
we can swap this over to a [state](https://gamut.codecademy.com/?path=/docs/foundations-system-variants--page) pretty nicely!

2022-04-11 14:58 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.e63ce0.0<br/>@codecademy/gamut-labs@31.3.4-alpha.e63ce0.0<br/>@codecademy/styleguide@56.2.4-alpha.e63ce0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-11 15:50 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +const StyledTitle = styled(Text)`
Stephens feedback about using 12:
> That makes sense, it's definitely a rich + complex surface that would warrant using the smaller text. Down to ship with a smaller text override and do a follow-up on this after that

2022-04-11 16:09 UTC, dreamwasp reviewed
is there a way to navigate through this menu with the keyboard? i'm also noticing i'm now able to open other dropdowns on top of it
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/58054751/162783766-36dbe4b6-5464-401e-88bd-581f590587e7.png">

2022-04-11 16:28 UTC, thedoomshine requested changes
i have a lot of accessibility concerns with this change, could we have a meeting with the disco and web plat teams to discuss them?

2022-04-11 21:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.99-alpha.b5d1a1.0<br/>@codecademy/gamut-labs@31.3.4-alpha.b5d1a1.0<br/>@codecademy/styleguide@56.2.4-alpha.b5d1a1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-04-11 21:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6254a3b35360a2351f2113ab--gamut-preview.netlify.app>https://6254a3b35360a2351f2113ab--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6254a3b35360a2351f2113ab>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-04-12 15:35 UTC, borisonr approved these changes

2022-04-12 19:57 UTC, thedoomshine approved these changes
looks good!

2022-04-12 21:06 UTC, dreamwasp approved these changes
perfection ✨

2022-04-12 21:32 UTC, merged