Rb ds nav disc 697
Codecademy/gamut pull request #2422
Opened 2022-06-21 17:54 UTC by borisonr

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2022-06-21 17:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.146-alpha.f9bb66.0<br/>@codecademy/gamut-labs@32.1.1-alpha.f9bb66.0<br/>@codecademy/styleguide@58.0.9-alpha.f9bb66.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-06-21 17:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b206fe6e8f7a0da1e9d926--gamut-preview.netlify.app>https://62b206fe6e8f7a0da1e9d926--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b206fe6e8f7a0da1e9d926>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-21 18:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b20a2695ad320e46169960--gamut-preview.netlify.app>https://62b20a2695ad320e46169960--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b20a2695ad320e46169960>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-21 18:28 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.146-alpha.2abc2b.0<br/>@codecademy/gamut-labs@32.1.1-alpha.2abc2b.0<br/>@codecademy/styleguide@58.0.9-alpha.2abc2b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-06-21 19:05 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.146-alpha.065cb1.0<br/>@codecademy/gamut-labs@32.1.1-alpha.065cb1.0<br/>@codecademy/styleguide@58.0.9-alpha.065cb1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-06-21 19:07 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b216c7f0c5b31b5b3a30ef--gamut-preview.netlify.app>https://62b216c7f0c5b31b5b3a30ef--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b216c7f0c5b31b5b3a30ef>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-21 21:24 UTC, aresnik11 commented
@borisonr hey! how do i trigger the new catalog menu? thanks!

2022-06-22 14:37 UTC, aresnik11 commented
> > @borisonr hey! how do i trigger the new catalog menu? thanks!
> 
> hmm you dont automatically see it? i have the variant on to 100% in non-prod envs @aresnik11

ah i see it if i'm logged in

2022-06-22 14:40 UTC, borisonr commented
> > > @borisonr hey! how do i trigger the new catalog menu? thanks!
> > 
> > 
> > hmm you dont automatically see it? i have the variant on to 100% in non-prod envs @aresnik11
> 
> ah i see it if i'm logged in

oh you might have been cached into the control before i turned the variant up to 100%

2022-06-22 14:54 UTC, zippyzow approved these changes
These changes look good on my end

2022-06-22 15:53 UTC, aresnik11 requested changes
I'm unable to click on any of the links in the dropdown. They look like links and I can see that it is an anchor element, but clicking on it doesn't do anything.

I was also able to open the resources menu on top of the catalog menu a few times, still trying to figure out how to consistently replicate that though
<img width="1421" alt="Screen Shot 2022-06-22 at 11 19 16 AM" src="https://user-images.githubusercontent.com/8761638/175074785-b17697e0-7200-4f45-8440-0c491f549e61.png">

2022-06-22 16:13 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.148-alpha.2ebee4.0<br/>@codecademy/gamut-labs@32.2.1-alpha.2ebee4.0<br/>@codecademy/styleguide@58.1.1-alpha.2ebee4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-06-22 16:15 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b34025c6dc3a203e5a58fd--gamut-preview.netlify.app>https://62b34025c6dc3a203e5a58fd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b34025c6dc3a203e5a58fd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-22 17:42 UTC, zippyzow commented
> this is so weird, i'm kind of stumped... it works if you make the screen smaller so that it's the hamburger menu... any ideas what may be happening @zippyzow or @aresnik11 ? (re links not being clickable, i cant reproduce the overlap with the resources dropdown) also interestingly it works if you tab/arrow into it

Taking a look on my branch, I'll let you know if I figure it out

2022-06-22 17:43 UTC, aresnik11 commented
> this is so weird, i'm kind of stumped... it works if you make the screen smaller so that it's the hamburger menu... any ideas what may be happening @zippyzow or @aresnik11 ? (re links not being clickable, i cant reproduce the overlap with the resources dropdown) also interestingly it works if you tab/arrow into it

also looking! i've confirmed what you said re links work in hamburger menu but not in regular dropdown, and they work if you access via keyboard and click enter

2022-06-22 18:43 UTC, zippyzow commented
@borisonr I placed the anchor directly inside of the `StyledAnchorColumn` and it worked (like screenshot below). Seems like there needs to be a separate `onClick` handler to trigger the `onClick` handler in the `CatalogLink` component or something. 

![Screen Shot 2022-06-22 at 2 41 23 PM](https://user-images.githubusercontent.com/12686946/175112466-8c52331e-3e2d-4544-9c90-1c04f026a9ad.png)

2022-06-22 18:51 UTC, borisonr commented
> @borisonr I placed the anchor directly inside of the `StyledAnchorColumn` and it worked (like screenshot below). Seems like there needs to be a separate `onClick` handler to trigger the `onClick` handler in the `CatalogLink` component or something.
> 
> ![Screen Shot 2022-06-22 at 2 41 23 PM](https://user-images.githubusercontent.com/12686946/175112466-8c52331e-3e2d-4544-9c90-1c04f026a9ad.png)

ahh amazing find, thank you @zippyzow !!

2022-06-22 18:53 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +                    <Anchor
there was a bunch of excess css i was able to remove so there became less of a need to set up the cataloglink component anyway but lemme know if you want me to keep that and properly scope the click handler

2022-06-22 19:06 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +                    <Anchor
This is good with me

2022-06-22 19:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.148-alpha.7f09cd.0<br/>@codecademy/gamut-labs@32.2.1-alpha.7f09cd.0<br/>@codecademy/styleguide@58.1.1-alpha.7f09cd.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-06-22 19:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b37051baf8fd1f6cbd77f0--gamut-preview.netlify.app>https://62b37051baf8fd1f6cbd77f0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b37051baf8fd1f6cbd77f0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-22 21:49 UTC, aresnik11 reviewed
The "explore full catalog" link still isn't clickable but the rest of them work as expected! Also noticed that "Cybersecurity" and "Machine Learning" aren't accessible via keyboard. Is the capitalization on "Top career Paths" correct? seems off to me, but I'll defer to you/your designer.

Re the double menu issue, I have replication steps now but I can replicate on 2 dropdowns in the app header outside of the mega menu so I'm going to make a bug ticket for web plat

2022-06-23 13:26 UTC, borisonr commented
> The "explore full catalog" link still isn't clickable but the rest of them work as expected! Also noticed that "Cybersecurity" and "Machine Learning" aren't accessible via keyboard. Is the capitalization on "Top career Paths" correct? seems off to me, but I'll defer to you/your designer.
> 
> Re the double menu issue, I have replication steps now but I can replicate on 2 dropdowns in the app header outside of the mega menu so I'm going to make a bug ticket for web plat

thank you for all the thorough QA @aresnik11 ! just pushed those fixes and will rerequest after i update the preview envs

2022-06-23 13:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62b46ba93fcb4523bdd03248--gamut-preview.netlify.app>https://62b46ba93fcb4523bdd03248--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62b46ba93fcb4523bdd03248>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-06-23 17:47 UTC, merged