Vb clickable page sinle feature image
Codecademy/gamut pull request #2447
Opened 2022-07-06 12:32 UTC by vonbarown

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2022-07-06 12:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.153-alpha.f876e1.0<br/>@codecademy/gamut-labs@32.4.1-alpha.f876e1.0<br/>@codecademy/styleguide@58.1.8-alpha.f876e1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-06 12:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62c5829ac28dad1dacb48ca3--gamut-preview.netlify.app>https://62c5829ac28dad1dacb48ca3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62c5829ac28dad1dacb48ca3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-06 16:42 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.153-alpha.d59ef5.0<br/>@codecademy/gamut-labs@32.4.1-alpha.d59ef5.0<br/>@codecademy/styleguide@58.1.8-alpha.d59ef5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-06 16:45 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62c5bc06abe5d803727287e6--gamut-preview.netlify.app>https://62c5bc06abe5d803727287e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62c5bc06abe5d803727287e6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-11 12:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.156-alpha.094012.0<br/>@codecademy/gamut-labs@32.6.1-alpha.094012.0<br/>@codecademy/styleguide@58.1.11-alpha.094012.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-11 12:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62cc1e13e304240608f858b6--gamut-preview.netlify.app>https://62cc1e13e304240608f858b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62cc1e13e304240608f858b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-11 13:10 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.156-alpha.92f591.0<br/>@codecademy/gamut-labs@32.6.1-alpha.92f591.0<br/>@codecademy/styleguide@58.1.11-alpha.92f591.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-11 13:13 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62cc21da08f44e095b672817--gamut-preview.netlify.app>https://62cc21da08f44e095b672817--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62cc21da08f44e095b672817>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-11 14:28 UTC, dreamwasp commented
@vonbarown please fill out the [testing instructions](https://i.imgur.com/sy93D9I.png)

2022-07-11 14:55 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.156-alpha.b26a74.0<br/>@codecademy/gamut-labs@32.6.1-alpha.b26a74.0<br/>@codecademy/styleguide@58.1.11-alpha.b26a74.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-11 14:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62cc3a5bbf3a862331c7df78--gamut-preview.netlify.app>https://62cc3a5bbf3a862331c7df78--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62cc3a5bbf3a862331c7df78>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-11 15:08 UTC, aresnik11 commented
@vonbarown fun fact! instead of changing the code to add `preview: true` you can just go to http://localhost:3100/api/portal/preview?path=pages/business and that enables preview mode. you'll be able to tell because there's an alert banner telling you this is contentful preview mode

2022-07-11 15:11 UTC, vonbarown commented
> @vonbarown fun fact! instead of changing the code to add `preview: true` you can just go to http://localhost:3100/api/portal/preview?path=pages/business and that enables preview mode. you'll be able to tell because there's an alert banner telling you this is contentful preview mode

Thanks, save a lot of head 😆

2022-07-11 21:15 UTC, dreamwasp requested changes
just wanna make sure this is accessible before ✅

2022-07-11 21:15 UTC, dreamwasp commented on packages/gamut-labs/src/LandingPage/PageSingleFeature.tsx
> +    >
did some[ brief research](https://usability.yale.edu/web-accessibility/articles/images) and images as links should probably require alt text, maybe worth tagging @Codecademy/accessibility and/or posting in the accessibility slack channel

2022-07-11 21:15 UTC, dreamwasp commented on packages/styleguide/stories/Brand Labs/Organisms/PageSingleFeature.stories.mdx
> +## Linakble Image
*Linkable

2022-07-11 21:24 UTC, vonbarown commented on packages/gamut-labs/src/LandingPage/PageSingleFeature.tsx
> +    >
should the link have the alt text as well?  This component has the alt text as required

2022-07-12 16:49 UTC, vonbarown commented on packages/gamut-labs/src/LandingPage/PageSingleFeature.tsx
> +    >
When running this through voice over, it announces that it is a link and an image with the alt tag
<img width="725" alt="Screen Shot 2022-07-12 at 11 45 04 AM" src="https://user-images.githubusercontent.com/52142269/178533744-a033d714-7559-4fd7-a4e0-397deb804610.png">

2022-07-13 15:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.156-alpha.be19c8.0<br/>@codecademy/gamut-labs@32.6.1-alpha.be19c8.0<br/>@codecademy/styleguide@58.1.11-alpha.be19c8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-07-13 15:10 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62cee03f1f72a733359b61b4--gamut-preview.netlify.app>https://62cee03f1f72a733359b61b4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62cee03f1f72a733359b61b4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-07-14 13:04 UTC, dreamwasp approved these changes
nice!

2022-07-14 14:33 UTC, merged