fix(Tooltip): fix useLayoutEffect ssr warning
Codecademy/gamut pull request #2517
Opened 2022-08-19 19:47 UTC by xendke

### Overview

### PR Checklist

- [x] Related to designs: None
- [x] Related to JIRA ticket: None
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2022-08-19 19:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.183-alpha.da947b.0<br/>@codecademy/gamut-labs@33.1.4-alpha.da947b.0<br/>@codecademy/gamut@50.4.2-alpha.da947b.0<br/>@codecademy/monaco@0.6.75-alpha.da947b.0<br/>@codecademy/styleguide@61.2.2-alpha.da947b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-19 19:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://62ffea0e73d245367e1fa3f3--gamut-preview.netlify.app>https://62ffea0e73d245367e1fa3f3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/62ffea0e73d245367e1fa3f3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-22 15:33 UTC, jakemhiller requested changes

2022-08-22 15:33 UTC, jakemhiller commented on packages/gamut/src/ToolTip/ToolTip.tsx
> +};
is there a reason not to exclude both from SSR? since they don't need to show up immediately?

2022-08-22 15:45 UTC, xendke commented on packages/gamut/src/ToolTip/ToolTip.tsx
> +};
The ToolTip component renders the `target` component inside. so preventing them from SSR would mean these little icons would not SSR.

![Screen Shot 2022-08-22 at 11 44 24 AM](https://user-images.githubusercontent.com/1364447/185962804-39cc066c-824c-4187-a798-5fd6b909abab.png)

2022-08-22 16:54 UTC, jakemhiller commented on packages/gamut/src/ToolTip/ToolTip.tsx
> +};
hm, fair enough. i feel like there's a better solution here that doesn't involve re-rendering the target on load, but this should work for now

2022-08-24 16:08 UTC, jakemhiller approved these changes

2022-08-24 17:16 UTC, merged