Refactor app header dropdown
Codecademy/gamut pull request #2519
Opened 2022-08-22 16:44 UTC by medhatnar

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: ABC-123
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2022-08-22 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Codecademy/gamut?pullRequest=2519) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/gamut?pullRequest=2519) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/gamut?pullRequest=2519) it.</sub>

2022-08-22 18:44 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.184-alpha.311be3.0<br/>@codecademy/gamut-labs@33.1.5-alpha.311be3.0<br/>@codecademy/styleguide@61.2.3-alpha.311be3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-22 18:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6303cefaae08e8179acac421--gamut-preview.netlify.app>https://6303cefaae08e8179acac421--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6303cefaae08e8179acac421>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-23 20:47 UTC, zippyzow reviewed
This is look great so far 🤌 ! Few questions/comments.

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/index.tsx
> +      const catalogItemCount = languageAndSubjectCount(item);
nit: if were just using `catalogItemCount` once, id say we can just inline it like below

```suggestion
```

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          itemsCount={catalogItemCount}
nit: if were just using `catalogItemCount` here and not any place else, id say we can just do 
```suggestion
          itemsCount={languageAndSubjectCount(item)}
```

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  isOpen?: boolean;
looks like we still need the following in `AppHeaderCatalogSectionProps` to resolve the ts errors in `AppHeader`?
```
role?: string;
id?: string;
```

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderResourcesSection/index.tsx
>    isOpen?: boolean;
looks like we still need the following in `AppHeaderResourcesSectionProps` to resolve the ts errors in `AppHeader`?
```
role?: string;
id?: string;
```

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/lib/catalogList/index.tsx
> +};
great idea moving this here and `resourcesItemCount` below

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdownSectionContainer/index.tsx
> +            })}
question: can you explain why we need to `isValidElement` and what the difference is between returning the cloned child vs the og child?

2022-08-23 20:47 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  isOpen?: boolean;
and `handleClose?: () => void;` for `AppHeaderSubMenuMobile`? Feels off though because it along with `role` and `id` are not being passed as props

2022-08-23 20:57 UTC, medhatnar commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  isOpen?: boolean;
Yeah I was confused because `role `and `id` are being passed but not used in the section components. I actually reintroduced them despite that just incase ts was mad.

2022-08-23 21:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.184-alpha.1388c2.0<br/>@codecademy/gamut-labs@33.1.5-alpha.1388c2.0<br/>@codecademy/styleguide@61.2.3-alpha.1388c2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-23 21:02 UTC, medhatnar commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdownSectionContainer/index.tsx
> +            })}
isValidElement is a safeguard that prevents the function running on a non-element. Without it ts complained. 

I need to pass in `isOpen` state to the children component but I don't know who the chlidren are going to be ahead of time so this is how I figured we could pass the `isOpen` prop to any child components of `AppHeaderDropdownSectionContainer`

I wasn't sure of another way to do this :<

2022-08-23 21:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.185-alpha.40d15f.0<br/>@codecademy/gamut-labs@33.1.6-alpha.40d15f.0<br/>@codecademy/styleguide@61.2.4-alpha.40d15f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-23 21:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6305428faa0453005a73df35--gamut-preview.netlify.app>https://6305428faa0453005a73df35--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6305428faa0453005a73df35>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-24 18:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.189-alpha.24e013.0<br/>@codecademy/gamut-labs@33.1.10-alpha.24e013.0<br/>@codecademy/styleguide@61.3.3-alpha.24e013.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-24 18:33 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://63066ec1238938169b531cb4--gamut-preview.netlify.app>https://63066ec1238938169b531cb4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/63066ec1238938169b531cb4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-24 18:48 UTC, zippyzow commented
Can you update the "PR Links and Envs" section in the testing instructions with the new monolith links and portal links?

2022-08-29 16:27 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.193-alpha.87ae07.0<br/>@codecademy/gamut-labs@33.2.1-alpha.87ae07.0<br/>@codecademy/styleguide@61.4.1-alpha.87ae07.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-29 16:29 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630ce9521ab82d0c86f02853--gamut-preview.netlify.app>https://630ce9521ab82d0c86f02853--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630ce9521ab82d0c86f02853>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-29 18:41 UTC, zippyzow approved these changes

2022-08-29 18:48 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  isOpen?: boolean;
should role and id be optional?

2022-08-29 18:53 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          styles={{
not a blocker but we could just pass in left instead of a styles object

2022-08-29 19:30 UTC, borisonr requested changes

2022-08-29 19:30 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdownSectionContainer/index.tsx
> +                return React.cloneElement(child, { isOpen, handleClose });
we need to implement the handleClose for the mobile dropdown too

2022-08-29 22:02 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
> +  isOpen?: boolean;
looks like `role` was optional previously, so I will add that `?` back in. I also see `id` wasn't added but I don't see the typescript error I was seeing before in `AppHeader` (mentioned in first comment) so I'm assuming Nar addressed that elsewhere.

2022-08-29 22:04 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          styles={{
do you mean removing 
```
styles={{top: '3.5rem',
            minWidth: '64rem',
            left: isAnon ? '-9rem' : '-14rem',
          }}
```
 and just doing `left: isAnon ? '-9rem' : '-14rem'` Are you seeing `top` and `midWidth` being passed elsewhere?

2022-08-29 22:46 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          styles={{
ah no, i mean instead of setting a `styles` prop, in the shared component we can set top and minwidth bc they're the same for catalog and resources, and then just pass in a prop called `left`. but this is not necessary

2022-08-30 14:09 UTC, zippyzow commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          styles={{
oh ok gotcha

2022-08-30 18:53 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.193-alpha.51e87e.0<br/>@codecademy/gamut-labs@33.2.1-alpha.51e87e.0<br/>@codecademy/styleguide@61.4.1-alpha.51e87e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-30 18:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630e5cda386b052572941efc--gamut-preview.netlify.app>https://630e5cda386b052572941efc--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630e5cda386b052572941efc>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-30 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.9e423c.0<br/>@codecademy/gamut-labs@33.2.2-alpha.9e423c.0<br/>@codecademy/styleguide@61.4.2-alpha.9e423c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-30 19:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630e62eddd7b2d0086db0803--gamut-preview.netlify.app>https://630e62eddd7b2d0086db0803--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630e62eddd7b2d0086db0803>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-30 20:09 UTC, borisonr commented on packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdownSectionContainer/index.tsx
> +                return React.cloneElement(child, { isOpen, handleClose });
so i think this was how nar refactored the handleClose (line 232) and we don't need both this and adding handleclose in the section components, nar just missed the mobile container? we can probably just revert to how i had it before for now, and let nar handle it for mobile and desktop when they're back unless you want to try to implement this cloneelement logic for the mobile container?

2022-08-30 21:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.91d239.0<br/>@codecademy/gamut-labs@33.2.2-alpha.91d239.0<br/>@codecademy/styleguide@61.4.2-alpha.91d239.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-30 21:58 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630e880014c7c8052dfb28f3--gamut-preview.netlify.app>https://630e880014c7c8052dfb28f3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630e880014c7c8052dfb28f3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-31 14:18 UTC, dreamwasp commented on packages/gamut-labs/src/AppHeader/index.tsx
> +          styles={{
you could [compose](https://gamut.codecademy.com/?path=/docs/foundations-system-compose--page) this component with the system props [categories](https://gamut.codecademy.com/?path=/docs/foundations-system-props--layout) positioning + layout to give it direct access in inline props

2022-09-02 14:33 UTC, zippyzow requested changes
Nar, see feedback around [mobile handleClose](https://github.com/Codecademy/gamut/pull/2519#discussion_r958884873). We can discuss when you're back as well.

2022-10-18 17:38 UTC, closed without merging