feat(GlobalHeader): Add business logic for Skillsoft users for BAM profile menu item
Codecademy/gamut pull request #2532
Opened 2022-08-29 19:30 UTC by jenesh

### Overview

We want to feature flag the `Business Account Management` profile menu item for skillsoft users. This PR adds two fields, one to check for a skillsoft user and the other to check if the feature flag to show the BAM in the menu is on or off.

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [EN-1954]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

To test just need to confirm that the `GlobalHeader` has the two new fields (`isSkillsoftUser` and `skillsoftBamProfileFeatureFlag`) under `user`:

<img width="492" alt="Screen Shot 2022-08-30 at 11 07 37 AM" src="https://user-images.githubusercontent.com/47792836/187473088-4a099d2d-1df6-468e-ab2e-b03742ec507a.png">

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](https://github.com/codecademy-engineering/Codecademy/pull/32255)  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](https://github.com/codecademy-engineering/portal-app/pull/2503)  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[EN-1954]: https://codecademy.atlassian.net/browse/EN-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-08-29 19:34 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.191-alpha.47c44f.0<br/>@codecademy/gamut-labs@33.1.12-alpha.47c44f.0<br/>@codecademy/styleguide@61.3.5-alpha.47c44f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-29 19:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630d1564cfd2db183833efdd--gamut-preview.netlify.app>https://630d1564cfd2db183833efdd--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630d1564cfd2db183833efdd>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-30 14:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.fc8f8b.0<br/>@codecademy/gamut-labs@33.2.2-alpha.fc8f8b.0<br/>@codecademy/styleguide@61.4.2-alpha.fc8f8b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-30 14:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630e21cf44eb296aa73e4df5--gamut-preview.netlify.app>https://630e21cf44eb296aa73e4df5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630e21cf44eb296aa73e4df5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-30 17:34 UTC, dreamwasp commented on packages/gamut-labs/src/GlobalHeader/types.tsx
> +  hasNewSkuSubscription?: boolean;
is this related to these changes?

2022-08-30 17:36 UTC, dreamwasp requested changes
still seeing related test failures in [portal-app](https://app.circleci.com/pipelines/github/codecademy-engineering/portal-app/13633/workflows/e5afb08f-b17e-43db-aade-28bb5f4695f3/jobs/143053)

2022-08-30 17:56 UTC, jenesh commented on packages/gamut-labs/src/GlobalHeader/types.tsx
> +  hasNewSkuSubscription?: boolean;
oh that must have slipped when updating branch with main

2022-08-30 17:57 UTC, jenesh commented
> still seeing related test failures in [portal-app](https://app.circleci.com/pipelines/github/codecademy-engineering/portal-app/13633/workflows/e5afb08f-b17e-43db-aade-28bb5f4695f3/jobs/143053)

That userGeo is not related to my changes... hmm maybe someone has pushed a fix for that I'll try merging in latest develop in portal PR

2022-08-30 18:01 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.776ab9.0<br/>@codecademy/gamut-labs@33.2.2-alpha.776ab9.0<br/>@codecademy/styleguide@61.4.2-alpha.776ab9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-30 18:03 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630e50eef8bb5315be6f9dd7--gamut-preview.netlify.app>https://630e50eef8bb5315be6f9dd7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630e50eef8bb5315be6f9dd7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-30 19:04 UTC, CharlieBliss requested changes

2022-08-30 19:04 UTC, CharlieBliss commented on packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
> +  const isSkillsoftUser = user?.isSkillsoftUser;
IMO we should make this more generic to prevent cluttering up gamut with business logic. The components shouldn't have to know about the state of the business data, just the state of their internal parts. This should be more like showBusinessAccount or something like that -- a boolean whose value is determined by the app that's using the component

2022-08-31 14:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.5d5776.0<br/>@codecademy/gamut-labs@33.2.2-alpha.5d5776.0<br/>@codecademy/styleguide@61.4.2-alpha.5d5776.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-31 14:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630f70e5e915181f2fb68501--gamut-preview.netlify.app>https://630f70e5e915181f2fb68501--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630f70e5e915181f2fb68501>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-31 16:27 UTC, CharlieBliss requested changes

2022-08-31 18:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.657b1a.0<br/>@codecademy/gamut-labs@33.2.2-alpha.657b1a.0<br/>@codecademy/styleguide@61.4.2-alpha.657b1a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-31 18:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630fa77c5aa93a0f724dfc2d--gamut-preview.netlify.app>https://630fa77c5aa93a0f724dfc2d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630fa77c5aa93a0f724dfc2d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-31 19:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.194-alpha.d9d150.0<br/>@codecademy/gamut-labs@33.2.2-alpha.d9d150.0<br/>@codecademy/styleguide@61.4.2-alpha.d9d150.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2022-08-31 19:20 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://630fb450d02b921b10240673--gamut-preview.netlify.app>https://630fb450d02b921b10240673--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/630fb450d02b921b10240673>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2022-08-31 19:50 UTC, CharlieBliss approved these changes

2022-08-31 20:11 UTC, dreamwasp approved these changes
✅

2022-09-01 13:15 UTC, merged