feat(webpack-config): bump in order to use dart sass
Codecademy/gamut pull request #2707
Opened 2023-03-30 14:40 UTC by jrood

### Overview

bump webpack-config package in order to use dart sass

### PR Checklist

- [ ] ~Related to designs:~
- [ ] ~Related to JIRA ticket: [ABC-123]~
- [x] I have run this code to verify it works
- [ ] ~This PR includes unit tests for the code change~
- [ ] ~This PR includes testing instructions tests for the code change~
- [ ] ~The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories~

#### PR Links and Envs
(no gamut kit alpha package generated)

2023-03-30 15:35 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6425ac297f8f790acc368668--gamut-preview.netlify.app>https://6425ac297f8f790acc368668--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6425ac297f8f790acc368668>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-03 14:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@64.0.6-alpha.3752ab.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-03 14:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642ae1e4b233892f5d77a3fe--gamut-preview.netlify.app>https://642ae1e4b233892f5d77a3fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642ae1e4b233892f5d77a3fe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-03 14:37 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@64.0.6-alpha.612ae2.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-03 14:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642ae4fc6bcf2c31a050824f--gamut-preview.netlify.app>https://642ae4fc6bcf2c31a050824f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642ae4fc6bcf2c31a050824f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-03 22:19 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@64.1.2-alpha.cf7a2f.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-03 22:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642b51493144004bc912b14e--gamut-preview.netlify.app>https://642b51493144004bc912b14e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642b51493144004bc912b14e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-05 20:03 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@64.1.3-alpha.ddfa95.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-05 20:05 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642dd474011b042139bf527c--gamut-preview.netlify.app>https://642dd474011b042139bf527c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642dd474011b042139bf527c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-06 14:40 UTC, jakemhiller requested changes

2023-04-06 14:40 UTC, jakemhiller commented on yarn.lock
> +node-sass@^6.0.1:
i think if you remove `node-sass` from the `resolutions` field in `package.json` it will be removed completely

2023-04-06 14:50 UTC, jrood commented on yarn.lock
> +node-sass@^6.0.1:
ah, good catch! I just removed it from resolutions, re-ran yarn, and I see that it's gone from the yarn lock also.

2023-04-06 14:59 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/styleguide@64.1.3-alpha.17c42b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-06 15:36 UTC, merged