updated social media sharing to be an ul
Codecademy/gamut pull request #2711
Opened 2023-04-04 21:53 UTC by medhatnar

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2023-04-04 22:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.303-alpha.7d96e8.0<br/>@codecademy/gamut-labs@35.11.1-alpha.7d96e8.0<br/>@codecademy/styleguide@64.1.2-alpha.7d96e8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-04 22:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642caa62951d590a100eb894--gamut-preview.netlify.app>https://642caa62951d590a100eb894--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642caa62951d590a100eb894>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-05 17:25 UTC, medhatnar commented on packages/gamut-labs/src/SocialMediaSharing/SocialShareIconLink.tsx
> +const IconLink = styled(Anchor)``;
removing `Box` component from styled definition

2023-04-05 17:25 UTC, medhatnar commented on packages/gamut-labs/src/SocialMediaSharing/SocialShareIconLink.tsx
> +    <Box as="li">
Included `Box` component in here instead so it maintains original shape and we can explicitly define it as an `li`

2023-04-05 17:26 UTC, medhatnar commented on packages/gamut-labs/src/SocialMediaSharing/index.tsx
> +      <UnstyledUnorderedList
updated this `Gridbox` to be as `ul`

2023-04-05 21:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.304-alpha.907bd9.0<br/>@codecademy/gamut-labs@35.11.2-alpha.907bd9.0<br/>@codecademy/styleguide@64.1.3-alpha.907bd9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-05 21:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642ded374143e80890f2ca0d--gamut-preview.netlify.app>https://642ded374143e80890f2ca0d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642ded374143e80890f2ca0d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-06 16:44 UTC, zippyzow commented
@medhatnar could you include testing instructions for this?

2023-04-06 16:54 UTC, christian-dinh commented
making the `GridBox` a `ul` adds some default padding and margin from the user agent styles:

<img width="420" alt="Screen Shot 2023-04-06 at 12 52 50 PM" src="https://user-images.githubusercontent.com/19958143/230444850-3b9ded2a-d750-493f-8987-caca589dd5fb.png">

2023-04-06 18:11 UTC, medhatnar commented
> @medhatnar could you include testing instructions for this?

I will include them once Mono pr preview deploys

2023-04-06 18:20 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.304-alpha.d4a27b.0<br/>@codecademy/gamut-labs@35.11.2-alpha.d4a27b.0<br/>@codecademy/styleguide@64.2.1-alpha.d4a27b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-06 18:21 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://642f0d91f1fe8200bc9dd1ca--gamut-preview.netlify.app>https://642f0d91f1fe8200bc9dd1ca--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/642f0d91f1fe8200bc9dd1ca>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-07 18:04 UTC, dreamwasp reviewed
just made a small comment - will do full review when testing instructions are updated ✨

2023-04-07 18:04 UTC, dreamwasp commented on packages/gamut-labs/src/SocialMediaSharing/index.tsx
> +
the css utility function from gamut-styles would be useful here - docs are [here](https://gamut.codecademy.com/?path=/docs/foundations-system-variants--page) + there are some examples [here](https://www.notion.so/codecademy/Gamut-Best-Practices-ce542cb06ec04e38bf269efab0f6bbb1?pvs=4#b005826dae8a40218881c46547e1c7b6)

2023-04-11 14:14 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.44b1e5.0<br/>@codecademy/gamut-labs@35.11.4-alpha.44b1e5.0<br/>@codecademy/styleguide@64.2.3-alpha.44b1e5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-11 15:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.d89131.0<br/>@codecademy/gamut-labs@35.11.4-alpha.d89131.0<br/>@codecademy/styleguide@64.2.3-alpha.d89131.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-11 15:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64357f0bab39a822948737a4--gamut-preview.netlify.app>https://64357f0bab39a822948737a4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64357f0bab39a822948737a4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-11 19:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6435b0bf946ce932d4ab348c--gamut-preview.netlify.app>https://6435b0bf946ce932d4ab348c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6435b0bf946ce932d4ab348c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-11 21:35 UTC, zippyzow reviewed
Looks like some of the styling got wiped because the border styles are no longer being applied to a Box but instead an Anchor. 

**Prod**
<img width="917" alt="Screenshot 2023-04-11 at 5 28 35 PM" src="https://user-images.githubusercontent.com/12686946/231292455-2f05724f-b3eb-4001-bc07-7cf4a19c7b1f.png">

**Monolith PR Env**
<img width="985" alt="Screenshot 2023-04-11 at 5 28 39 PM" src="https://user-images.githubusercontent.com/12686946/231292457-7b1ed9cd-9f07-4bc0-8aa9-9d200480ba61.png">

2023-04-12 19:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.7753e4.0<br/>@codecademy/gamut-labs@35.11.4-alpha.7753e4.0<br/>@codecademy/styleguide@64.2.3-alpha.7753e4.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-12 19:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://643709981be6eb1c17fbed4c--gamut-preview.netlify.app>https://643709981be6eb1c17fbed4c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/643709981be6eb1c17fbed4c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-12 22:05 UTC, saghdaey approved these changes

2023-04-12 22:37 UTC, zippyzow requested changes
@medhatnar the learner stories and event page look good but the [quiz result page](https://pr-35303-monolith.dev-eks.codecademy.com/explore/sorting-quiz/results?advocator=38&connector=44&questioner=40&solver=37) needs a fix. The 0 margin on the `UnorderedListGridBox` seems to be taking precedence over the margin set in the `socialMediaIcons` css class in the `ArchetypeDetails` component. 

**PR env**
<img width="432" alt="Screenshot 2023-04-12 at 6 27 55 PM" src="https://user-images.githubusercontent.com/12686946/231600617-dabd4df1-5f99-42ed-80db-e4846ea6be42.png">
**Prod**
<img width="447" alt="Screenshot 2023-04-12 at 6 27 51 PM" src="https://user-images.githubusercontent.com/12686946/231600664-23744704-588c-4b8e-998d-a311c61a3add.png">

<img width="1591" alt="Screenshot 2023-04-12 at 6 33 06 PM" src="https://user-images.githubusercontent.com/12686946/231601033-f9323b5c-58ed-4253-be61-e9329c1e1408.png">

2023-04-13 13:11 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6437ff7b5e3f6a3772ffc1e0--gamut-preview.netlify.app>https://6437ff7b5e3f6a3772ffc1e0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6437ff7b5e3f6a3772ffc1e0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-13 13:46 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.89a795.0<br/>@codecademy/gamut-labs@35.11.4-alpha.89a795.0<br/>@codecademy/styleguide@64.2.3-alpha.89a795.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-13 13:49 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64380858d316de007fd4e709--gamut-preview.netlify.app>https://64380858d316de007fd4e709--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64380858d316de007fd4e709>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-13 14:52 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.e7c6dc.0<br/>@codecademy/gamut-labs@35.11.4-alpha.e7c6dc.0<br/>@codecademy/styleguide@64.2.3-alpha.e7c6dc.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-13 14:54 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6438179e300c83061d2b0924--gamut-preview.netlify.app>https://6438179e300c83061d2b0924--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6438179e300c83061d2b0924>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-13 15:40 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-kit@0.6.306-alpha.8d28ce.0<br/>@codecademy/gamut-labs@35.11.4-alpha.8d28ce.0<br/>@codecademy/styleguide@64.2.3-alpha.8d28ce.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-04-13 15:42 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://643822e3986ddf112d09bb27--gamut-preview.netlify.app>https://643822e3986ddf112d09bb27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/643822e3986ddf112d09bb27>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-04-13 19:05 UTC, dreamwasp approved these changes
nice!

2023-04-13 19:07 UTC, christian-dinh approved these changes

2023-04-13 20:50 UTC, merged