feat(Illustrations): Add computer lock illustration
Codecademy/gamut pull request #2751
Opened 2023-06-21 18:47 UTC by ahmed-abdallah

### Overview

Adds new computer + lock illustration

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [FLOW-514]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2023-06-21 18:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.38.1-alpha.15ef5a.0<br/>@codecademy/gamut-kit@0.6.330-alpha.15ef5a.0<br/>@codecademy/gamut-labs@35.15.3-alpha.15ef5a.0<br/>@codecademy/gamut@55.1.8-alpha.15ef5a.0<br/>@codecademy/monaco@0.7.34-alpha.15ef5a.0<br/>@codecademy/styleguide@66.1.12-alpha.15ef5a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-06-21 18:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://649347817f9538008807267f--gamut-preview.netlify.app>https://649347817f9538008807267f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/649347817f9538008807267f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-06-21 19:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.38.1-alpha.aebdc8.0<br/>@codecademy/gamut-kit@0.6.330-alpha.aebdc8.0<br/>@codecademy/gamut-labs@35.15.3-alpha.aebdc8.0<br/>@codecademy/gamut@55.1.8-alpha.aebdc8.0<br/>@codecademy/monaco@0.7.34-alpha.aebdc8.0<br/>@codecademy/styleguide@66.1.12-alpha.aebdc8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-06-21 19:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://64934ad12547ba06ef15a5f6--gamut-preview.netlify.app>https://64934ad12547ba06ef15a5f6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/64934ad12547ba06ef15a5f6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-06-21 19:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut-illustrations@0.38.1-alpha.91807c.0<br/>@codecademy/gamut-kit@0.6.330-alpha.91807c.0<br/>@codecademy/gamut-labs@35.15.3-alpha.91807c.0<br/>@codecademy/gamut@55.1.8-alpha.91807c.0<br/>@codecademy/monaco@0.7.34-alpha.91807c.0<br/>@codecademy/styleguide@66.1.12-alpha.91807c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-06-21 19:39 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://649351d5edd5790c34b052b8--gamut-preview.netlify.app>https://649351d5edd5790c34b052b8--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/649351d5edd5790c34b052b8>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-06-23 15:09 UTC, jakemhiller requested changes
curious about the illustrtation SVG, since it's mostly image data, is that expected?

2023-06-23 15:09 UTC, jakemhiller commented on packages/gamut-illustrations/src/ComputerLock.tsx
> +        xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABDgAAAQ4CAYAAADsEGyPAAAAAXNSR0IArs4c6QAAIABJREFUeF7s3S1cI8n28PHzuOCCm6y6GRccrBpGTXDBwaph1IIDB1cNowbUBQeOrFpQC444WDWMuuCIG67ajCOOuP/zqX
is it expected that this is an image, not SVG paths?

2023-06-26 11:52 UTC, ahmed-abdallah commented
Turns out this is a gif not an SVG at all

2023-06-26 11:52 UTC, closed without merging