Kl web 2446
Codecademy/gamut pull request #2793
Opened 2023-10-10 03:49 UTC by LinKCoding

### Overview
Addressing [WEB-2446](https://codecademy.atlassian.net/browse/WEB-2446) -- 
Adjust dark-mode`grey` badges variants to meet WCAG contrast 

### PR Checklist

- [ ] Related to designs: https://www.figma.com/file/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?type=design&node-id=29959-39721&mode=design&t=InPLnttaWm84srkv-0 
- [ ] Related to JIRA ticket: [WEB-2446]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2023-10-10 03:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.7.4-alpha.6f64f8.0<br/>@codecademy/gamut-kit@0.6.353-alpha.6f64f8.0<br/>@codecademy/styleguide@66.5.5-alpha.6f64f8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-10 03:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6524cb266b6e967a058d4846--gamut-preview.netlify.app>https://6524cb266b6e967a058d4846--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6524cb266b6e967a058d4846>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-10 04:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.7.4-alpha.88333a.0<br/>@codecademy/gamut-kit@0.6.353-alpha.88333a.0<br/>@codecademy/styleguide@66.5.5-alpha.88333a.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-10 04:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6524d007cade847e7ed74e81--gamut-preview.netlify.app>https://6524d007cade847e7ed74e81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6524d007cade847e7ed74e81>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-16 02:49 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.2-alpha.21a8e1.0<br/>@codecademy/gamut-kit@0.6.357-alpha.21a8e1.0<br/>@codecademy/styleguide@66.5.9-alpha.21a8e1.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-16 02:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://652ca4da1393ec63e56b2bc3--gamut-preview.netlify.app>https://652ca4da1393ec63e56b2bc3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/652ca4da1393ec63e56b2bc3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-19 02:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.2-alpha.a715f9.0<br/>@codecademy/gamut-kit@0.6.357-alpha.a715f9.0<br/>@codecademy/styleguide@66.5.9-alpha.a715f9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-19 02:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65309abcdf54425567d66872--gamut-preview.netlify.app>https://65309abcdf54425567d66872--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65309abcdf54425567d66872>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-19 14:34 UTC, dreamwasp requested changes
just have a couple tweaks to the storybook story then should be ready to ship!

2023-10-19 14:34 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/Badge.stories.mdx
>  Additional variants should designed with both <LinkTo kind='Foundations/ColorMode'>ColorModes</LinkTo> in mind. For example, the `yellow` and `grey` variants work against both light and dark backgrou
let's update the variant names in this paragraph as well

2023-10-19 14:34 UTC, dreamwasp commented on packages/styleguide/stories/Atoms/Badge.stories.mdx
>    <Story name="yellow" args={{ variant: 'yellow' }}>
this variant arg should be updated to `accent` and below (line 86) the `stroke` variant should be updated to `tertiary`

2023-10-19 14:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.2-alpha.47787b.0<br/>@codecademy/gamut-kit@0.6.357-alpha.47787b.0<br/>@codecademy/styleguide@66.5.9-alpha.47787b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-19 14:55 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6531435a8d203727df4b482e--gamut-preview.netlify.app>https://6531435a8d203727df4b482e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6531435a8d203727df4b482e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-24 14:51 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.8.2-alpha.703bf0.0<br/>@codecademy/gamut-kit@0.6.357-alpha.703bf0.0<br/>@codecademy/styleguide@66.5.9-alpha.703bf0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2023-10-24 14:53 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6537da6f26768805d4b9f768--gamut-preview.netlify.app>https://6537da6f26768805d4b9f768--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6537da6f26768805d4b9f768>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2023-10-24 14:53 UTC, merged