(feat: ProgressBar): adds flat prop to progressBar
Codecademy/gamut pull request #2844
Opened 2024-03-06 20:05 UTC by sooinc

### Overview

- adds `flat` prop to ProgresseBar

### PR Checklist

- [x] Related to designs: https://codecademy.atlassian.net/browse/GM-588
- [x] Related to JIRA ticket: [GM-588]
- [x] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2024-03-06 20:17 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.5-alpha.d28d2e.0<br/>@codecademy/gamut-kit@0.6.386-alpha.d28d2e.0<br/>@codecademy/styleguide@66.12.4-alpha.d28d2e.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-03-06 20:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e8cf59f661f14abd46a436--gamut-preview.netlify.app>https://65e8cf59f661f14abd46a436--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e8cf59f661f14abd46a436>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-03-06 22:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.5-alpha.d04f86.0<br/>@codecademy/gamut-kit@0.6.386-alpha.d04f86.0<br/>@codecademy/styleguide@66.12.4-alpha.d04f86.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-03-06 22:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65e8eb7d610661663ef8d75e--gamut-preview.netlify.app>https://65e8eb7d610661663ef8d75e--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65e8eb7d610661663ef8d75e>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-03-14 15:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.7-alpha.f62d15.0<br/>@codecademy/gamut-kit@0.6.388-alpha.f62d15.0<br/>@codecademy/styleguide@66.13.1-alpha.f62d15.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-03-14 15:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f31a574ec438f12534ea27--gamut-preview.netlify.app>https://65f31a574ec438f12534ea27--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f31a574ec438f12534ea27>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-03-14 19:44 UTC, sylvanasantos approved these changes
✨

2024-03-14 19:50 UTC, sylvanasantos requested changes
Oooo I had already approved but I just realized while testing the mono repo PR that the curvature on the bar is off when you add the flat prop. Or at least it doesn't match the existing functionality on the new dashboard.

Staging
<img width="220" alt="Screenshot 2024-03-14 at 12 47 11 PM" src="https://github.com/Codecademy/gamut/assets/65558802/53cb500f-3797-4627-a9a0-344039170f0e">

PR Env
<img width="224" alt="Screenshot 2024-03-14 at 12 47 19 PM" src="https://github.com/Codecademy/gamut/assets/65558802/a8fdff15-c33a-40c1-ae2a-a7452746b9f7">

2024-03-14 20:42 UTC, sooinc commented
> Oooo I had already approved but I just realized while testing the mono repo PR that the curvature on the bar is off when you add the flat prop. Or at least it doesn't match the existing functionality on the new dashboard.
> 
> Staging <img alt="Screenshot 2024-03-14 at 12 47 11 PM" width="220" src="https://private-user-images.githubusercontent.com/65558802/312977137-53cb500f-3797-4627-a9a0-344039170f0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDcwNjksIm5iZiI6MTcxMDQ0Njc2OSwicGF0aCI6Ii82NTU1ODgwMi8zMTI5NzcxMzctNTNjYjUwMGYtMzc5Ny00NjI3LWE5YTAtMzQ0MDM5MTcwZjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIwMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZjE5NWQzODUzZWI0YTJlMDMwYTU2ZGIyMTBjYmVlNDgxYWIxZDY0MDNmODMyZjBhYzIyOGQ1N2MzN2M5M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c4ZlJkK02DBFCvZN3bPWrVUQ_tKUQ7JiiEH8BaeOptI">
> 
> PR Env <img alt="Screenshot 2024-03-14 at 12 47 19 PM" width="224" src="https://private-user-images.githubusercontent.com/65558802/312977189-a8fdff15-c33a-40c1-ae2a-a7452746b9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDcwNjksIm5iZiI6MTcxMDQ0Njc2OSwicGF0aCI6Ii82NTU1ODgwMi8zMTI5NzcxODktYThmZGZmMTUtYzMzYS00MGMxLWFlMmEtYTc0NTI3NDZiOWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDIwMDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OWU3YjM2N2U5ZjdhMmJlZTYxNjFjZDA5NDBhNGZlODY5OTUyMzUyNDliZjc3NGNlYThkYmIxYzQ2NDQ3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asSklpWji_BmQjqvZdgv8hY_cP3vaHQ6x9D_t8nij4w">

ah oops, thanks for catching! i just adjusted it.

2024-03-14 20:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.7-alpha.8f92eb.0<br/>@codecademy/gamut-kit@0.6.388-alpha.8f92eb.0<br/>@codecademy/styleguide@66.13.1-alpha.8f92eb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-03-14 20:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f3632b7ef5a92dd941fb28--gamut-preview.netlify.app>https://65f3632b7ef5a92dd941fb28--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f3632b7ef5a92dd941fb28>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-03-14 20:59 UTC, sylvanasantos approved these changes

2024-03-14 20:59 UTC, sylvanasantos commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
Is this an intended change? Also is this because imports haven't been automatically sorting when you save a file on vscode? Because same lol

2024-03-14 21:01 UTC, sooinc commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
oh no, for some reason this keeps getting updated. i reverted as i didnt mean to push!

2024-03-14 21:08 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.13.7-alpha.73dff8.0<br/>@codecademy/gamut-kit@0.6.388-alpha.73dff8.0<br/>@codecademy/styleguide@66.13.1-alpha.73dff8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-03-14 21:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://65f36741a7ffb332edc2ec81--gamut-preview.netlify.app>https://65f36741a7ffb332edc2ec81--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/65f36741a7ffb332edc2ec81>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-03-15 19:40 UTC, dreamwasp approved these changes
love it 🚢

2024-03-15 19:44 UTC, merged