(feat): Add icon to Anchor
Codecademy/gamut pull request #2878
Opened 2024-05-28 15:15 UTC by LinKCoding

### Overview
Adding an icon to the Anchor component. 

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [GM-704](https://codecademy.atlassian.net/browse/GM-704)
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

[GM-704]: https://codecademy.atlassian.net/browse/GM-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-31 14:50 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.2f60a5.0<br/>@codecademy/gamut-kit@0.6.411-alpha.2f60a5.0<br/>@codecademy/styleguide@66.21.2-alpha.2f60a5.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-05-31 14:52 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6659e41acf4d1951f463efb0--gamut-preview.netlify.app>https://6659e41acf4d1951f463efb0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6659e41acf4d1951f463efb0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-05-31 15:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6659ea6a37abf65165ca1e78--gamut-preview.netlify.app>https://6659ea6a37abf65165ca1e78--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6659ea6a37abf65165ca1e78>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-05-31 15:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.c8d38c.0<br/>@codecademy/gamut-kit@0.6.411-alpha.c8d38c.0<br/>@codecademy/styleguide@66.21.2-alpha.c8d38c.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-05-31 15:37 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6659eebe37abf65635ca1c67--gamut-preview.netlify.app>https://6659eebe37abf65635ca1c67--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6659eebe37abf65635ca1c67>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-05-31 15:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.f39777.0<br/>@codecademy/gamut-kit@0.6.411-alpha.f39777.0<br/>@codecademy/styleguide@66.21.2-alpha.f39777.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-05-31 15:48 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6659f1347ea6b0528d61456c--gamut-preview.netlify.app>https://6659f1347ea6b0528d61456c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6659f1347ea6b0528d61456c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-05-31 18:00 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.34236b.0<br/>@codecademy/gamut-kit@0.6.411-alpha.34236b.0<br/>@codecademy/styleguide@66.21.2-alpha.34236b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-05-31 18:02 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://665a10a4ea270e087ac148fe--gamut-preview.netlify.app>https://665a10a4ea270e087ac148fe--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/665a10a4ea270e087ac148fe>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-03 19:18 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.31b4b9.0<br/>@codecademy/gamut-kit@0.6.411-alpha.31b4b9.0<br/>@codecademy/styleguide@66.21.2-alpha.31b4b9.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-03 19:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://665e17283107ad3fba81710a--gamut-preview.netlify.app>https://665e17283107ad3fba81710a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/665e17283107ad3fba81710a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-03 19:36 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.8af183.0<br/>@codecademy/gamut-kit@0.6.411-alpha.8af183.0<br/>@codecademy/styleguide@66.21.2-alpha.8af183.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-03 19:38 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://665e1ba7e990e740184500a4--gamut-preview.netlify.app>https://665e1ba7e990e740184500a4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/665e1ba7e990e740184500a4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-07 18:36 UTC, dreamwasp commented on packages/gamut/src/Anchor/index.tsx
> +      center,
i think this is where the not-centeredness is coming from, we prob always want the icon to be centered esp vertically

2024-06-07 18:37 UTC, dreamwasp requested changes
looking good so far! just a couple notes: 

the icons look a little uncentered:
<img width="331" alt="image" src="https://github.com/Codecademy/gamut/assets/58054751/0263bea3-58f7-4c2d-b088-9b45671ff659">

you should be able to make the wrapper a flex container and style it like so to make it look like stacey's designs 
<img width="571" alt="image" src="https://github.com/Codecademy/gamut/assets/58054751/61b23774-5df0-488b-b914-8576de4289d2">
<img width="330" alt="image" src="https://github.com/Codecademy/gamut/assets/58054751/4b1d3f88-4945-4a68-95f2-226f02496a4b">

2024-06-07 21:06 UTC, LinKCoding commented
> looking good so far! just a couple notes:
> 
> the icons look a little uncentered: <img alt="image" width="331" src="https://private-user-images.githubusercontent.com/58054751/337754727-0263bea3-58f7-4c2d-b088-9b45671ff659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTQ3MjctMDI2M2JlYTMtNThmNy00YzJkLWIwODgtOWI0NTY3MWZmNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTczN2EzMmFiMjlmMGFjZGRlMjI2MGM5MjE1YWZiOWVjMDY2ZTdhMmJmMmZjM2NmZTY1ZWMzNjAzOWViODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZFfYYR1wPCz4Ze4om5Ep8X1QnmBqmENmV9cSMy6RnH0">
> 
> you should be able to make the wrapper a flex container and style it like so to make it look like stacey's designs <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/58054751/337754967-61b23774-5df0-488b-b914-8576de4289d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTQ5NjctNjFiMjM3NzQtNWRmMC00ODhiLWI5MTQtODU3NmRlNDI4OWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzJhYjI5Mjc4Mjc4YjJlMmU2N2RjODEyZTEyZTI1NjMyZjU2ODMzZTJmYTdjNThlZWQ2NmJhZjkzZDY0YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DrosihZvGrOvwiVI7iCE4xGvN6-E8f3wzp_8KrbvmqI"> <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/58054751/337755640-4b1d3f88-4945-4a68-95f2-226f02496a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTU2NDAtNGIxZDNmODgtNDk0NS00YTY4LTk1ZjItMjI2ZjAyNDk2YTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTdmYWQ2MjA1MzkwYzJkNjFmNjMzZDJhNTJiODQyNzU0ODQ3NGVlMzU3Nzg0MGQ2ZDYwMTZkYzQxNzhiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVKkTSuxwXZLfGsdE5D20y2vSE-E0iUXkgr4XEqpkhE">

Ah, I remember doing this, but because we need links to be inline I can't use `display:flex` unfortunately :\ 
I'm going to play around with `vertical-align` more but it doesn't look as centered as flex 👀 
Thanks!

2024-06-10 14:05 UTC, dreamwasp commented
> > looking good so far! just a couple notes:
> > the icons look a little uncentered: <img alt="image" width="331" src="https://private-user-images.githubusercontent.com/58054751/337754727-0263bea3-58f7-4c2d-b088-9b45671ff659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTQ3MjctMDI2M2JlYTMtNThmNy00YzJkLWIwODgtOWI0NTY3MWZmNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTczN2EzMmFiMjlmMGFjZGRlMjI2MGM5MjE1YWZiOWVjMDY2ZTdhMmJmMmZjM2NmZTY1ZWMzNjAzOWViODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZFfYYR1wPCz4Ze4om5Ep8X1QnmBqmENmV9cSMy6RnH0">
> > you should be able to make the wrapper a flex container and style it like so to make it look like stacey's designs <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/58054751/337754967-61b23774-5df0-488b-b914-8576de4289d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTQ5NjctNjFiMjM3NzQtNWRmMC00ODhiLWI5MTQtODU3NmRlNDI4OWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzJhYjI5Mjc4Mjc4YjJlMmU2N2RjODEyZTEyZTI1NjMyZjU2ODMzZTJmYTdjNThlZWQ2NmJhZjkzZDY0YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DrosihZvGrOvwiVI7iCE4xGvN6-E8f3wzp_8KrbvmqI"> <img alt="image" width="330" src="https://private-user-images.githubusercontent.com/58054751/337755640-4b1d3f88-4945-4a68-95f2-226f02496a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzMTUsIm5iZiI6MTcxNzc5MTAxNSwicGF0aCI6Ii81ODA1NDc1MS8zMzc3NTU2NDAtNGIxZDNmODgtNDk0NS00YTY4LTk1ZjItMjI2ZjAyNDk2YTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDIwMTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTdmYWQ2MjA1MzkwYzJkNjFmNjMzZDJhNTJiODQyNzU0ODQ3NGVlMzU3Nzg0MGQ2ZDYwMTZkYzQxNzhiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVKkTSuxwXZLfGsdE5D20y2vSE-E0iUXkgr4XEqpkhE">
> 
> Ah, I remember doing this, but because we need links to be inline I can't use `display:flex` unfortunately :\ I'm going to play around with `vertical-align` more but it doesn't look as centered as flex 👀 Thanks!

you could also try adding messing around with margin/padding `auto` or applying flex to just the container the icon is in!

2024-06-11 21:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.c20624.0<br/>@codecademy/gamut-kit@0.6.411-alpha.c20624.0<br/>@codecademy/styleguide@66.21.2-alpha.c20624.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-11 21:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6668c0a887ba4f092b8248eb--gamut-preview.netlify.app>https://6668c0a887ba4f092b8248eb--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6668c0a887ba4f092b8248eb>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-12 13:21 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.21.2-alpha.ff93eb.0<br/>@codecademy/gamut-kit@0.6.411-alpha.ff93eb.0<br/>@codecademy/styleguide@66.21.2-alpha.ff93eb.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-12 13:23 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6669a1357604122ad5f225f7--gamut-preview.netlify.app>https://6669a1357604122ad5f225f7--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6669a1357604122ad5f225f7>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-12 14:09 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.2-alpha.50978b.0<br/>@codecademy/gamut-kit@0.6.414-alpha.50978b.0<br/>@codecademy/styleguide@66.24.1-alpha.50978b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-12 14:12 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6669acac6363602cd50d76b6--gamut-preview.netlify.app>https://6669acac6363602cd50d76b6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6669acac6363602cd50d76b6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-12 15:17 UTC, LinKCoding commented on packages/styleguide/stories/Typography/Anchor.examples.tsx
> +export const VariantsExample = ({ useIcon }: { useIcon: boolean }) => {
opting only to use a boolean to render the icon or not for simplicity's sake.

2024-06-12 15:17 UTC, LinKCoding commented on packages/styleguide/stories/Typography/Anchor.examples.tsx
> +export const InlineAnchorWithIconAndText = ({ args }: { args: any }) => {
also keeping this as `any` for simplicity's sake.

2024-06-12 17:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.2-alpha.882f34.0<br/>@codecademy/gamut-kit@0.6.414-alpha.882f34.0<br/>@codecademy/styleguide@66.24.1-alpha.882f34.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-12 17:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6669d6185d9685007af2337c--gamut-preview.netlify.app>https://6669d6185d9685007af2337c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6669d6185d9685007af2337c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-12 19:07 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.2-alpha.1179ba.0<br/>@codecademy/gamut-kit@0.6.414-alpha.1179ba.0<br/>@codecademy/styleguide@66.24.1-alpha.1179ba.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-12 19:09 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6669f265ac27de1d0011db3f--gamut-preview.netlify.app>https://6669f265ac27de1d0011db3f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6669f265ac27de1d0011db3f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-13 15:16 UTC, dreamwasp commented on packages/styleguide/stories/Typography/Anchor.examples.tsx
> +export const InlineAnchorWithIconAndText = ({ args }: { args: any }) => {
i tested this locally and it worked for me! you may need to tweak the way you're passing the args, only tested for type safety herer

`export const InlineAnchorWithIconAndText: React.FC<AnchorProps> = (args) => {`

2024-06-13 20:18 UTC, LinKCoding commented on packages/styleguide/stories/Typography/Anchor.examples.tsx
> +export const InlineAnchorWithIconAndText = ({ args }: { args: any }) => {
Does that mean i need to do more than replace my line of code for what you wrote? 😂

2024-06-13 20:41 UTC, dreamwasp commented on packages/styleguide/stories/Typography/Anchor.examples.tsx
> +export const InlineAnchorWithIconAndText = ({ args }: { args: any }) => {
maybe just change the way you're passing args in the story!

2024-06-13 22:29 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.2-alpha.f51443.0<br/>@codecademy/gamut-kit@0.6.414-alpha.f51443.0<br/>@codecademy/styleguide@66.24.1-alpha.f51443.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-13 22:31 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666b7335e5d72bc8accf7e42--gamut-preview.netlify.app>https://666b7335e5d72bc8accf7e42--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666b7335e5d72bc8accf7e42>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-21 14:16 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66758b396a08c692f4eb4c1a--gamut-preview.netlify.app>https://66758b396a08c692f4eb4c1a--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66758b396a08c692f4eb4c1a>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-21 14:41 UTC, dreamwasp commented on packages/gamut/src/Anchor/index.tsx
> +    iconOffset = variant === 'inline' ? 2 : 4;
can you make this scalable using `em`s? you might need to cast it as an any but i'm wondering if that would fix our font iscaling ssues a bit! (`em`s are always relative to their parent components ✨ )

2024-06-21 14:41 UTC, dreamwasp reviewed
this looks great!! once the story is cleaned up i'm happy to ✅  even if the offset is left as is 🔥

2024-06-21 20:01 UTC, LinKCoding commented on packages/gamut/src/helpers/appendIconToContent.tsx
> +  const iconProps = {
This is to check if `iconOffset` is assigned a number (i.e. an override) -- but if it's just `undefined`, then 2 and 4 should work respectively.

2024-06-21 20:02 UTC, LinKCoding commented
pixels vs em comparison. 
the following SS show the diff between pixels and em offset implementations 
The top paragraph in the SS changes (and is noted in the text under the SS) the bottom text stays as 16px. 

![image](https://github.com/Codecademy/gamut/assets/25854220/d97678ad-718c-4c52-9516-ee015b0ac72e)
Just to note, the pixel implementation works well even when on larger font sizes. 

![image](https://github.com/Codecademy/gamut/assets/25854220/674fa27f-3ea3-4664-a94e-fbd81a8a1c62)
^ it looks off tho when font is smaller than 16px (it's 14 in the SS) 

![image](https://github.com/Codecademy/gamut/assets/25854220/4707321b-7034-40ea-b43d-72a12c32bc57)
^ this is with em, top text being 14px, it looks a bit more centered. 

![image](https://github.com/Codecademy/gamut/assets/25854220/e0bd5f7c-5db8-4b78-bc27-e4c9b5eab15b)
^ and this is size 22px with em. 

Gonna go ahead and make the change to em -- but @dreamwasp just to note, I added in a helper to convert px to em 
If there's a preferred library or a different implementation please lmk 🙏 
Thanks~

2024-06-21 20:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.6-alpha.a0bee8.0<br/>@codecademy/gamut-kit@0.6.418-alpha.a0bee8.0<br/>@codecademy/styleguide@66.26.1-alpha.a0bee8.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-21 20:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6675e1be769adadf7b58df16--gamut-preview.netlify.app>https://6675e1be769adadf7b58df16--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6675e1be769adadf7b58df16>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-24 14:26 UTC, dreamwasp approved these changes
this is wonderful, and thank you for being so thorough 🙏

2024-06-25 15:30 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.7-alpha.95a2b7.0<br/>@codecademy/gamut-kit@0.6.419-alpha.95a2b7.0<br/>@codecademy/styleguide@66.26.2-alpha.95a2b7.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-25 15:32 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://667ae30b9da3d01f18f5c1fa--gamut-preview.netlify.app>https://667ae30b9da3d01f18f5c1fa--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/667ae30b9da3d01f18f5c1fa>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-25 15:34 UTC, merged