chore(Button): updating IconButton's variants' icon sizes
Codecademy/gamut pull request #2887
Opened 2024-06-13 15:44 UTC by LinKCoding

### Overview
IconButtons use icons that currently size depending on the parent container using `"calc(100% - 14)"`
But for some reason this calculation seems to be done using the width/height of `::after` which can be marginally larger (e.g. 40.8 when it should be exactly 40)
![image](https://github.com/Codecademy/gamut/assets/25854220/9bd873ec-cf4d-4c6a-adf5-bf98ca6b1d4e)
^ on the prod version of storybook, it comes out to 40 🤷 

Regardless, the calculation of `-14px` should actually be `-18px` to enable a padding of 8px all around.

To make the sizing more explicit, concrete values were used:
normal: 24, <- from figma
small: 16, <- from figma
large: 40, <- assuming since currently a large IconButton is 56 and 56 - 16 = 40, the figma will need to be updated to reflect this size. 

### PR Checklist

- [ ] Related to designs: https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1106-90&m=dev
- [ ] Related to JIRA ticket: https://codecademy.atlassian.net/browse/GM-702 
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2024-06-13 15:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.4-alpha.163f33.0<br/>@codecademy/gamut-kit@0.6.416-alpha.163f33.0<br/>@codecademy/styleguide@66.25.1-alpha.163f33.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-13 15:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://666b16bc273aa9527803b3d5--gamut-preview.netlify.app>https://666b16bc273aa9527803b3d5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/666b16bc273aa9527803b3d5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-21 14:35 UTC, dreamwasp approved these changes
i have the tiniest of nits but this looks perfect! 🔥

2024-06-21 14:35 UTC, dreamwasp commented on packages/gamut/src/Button/IconButton.tsx
> +    const size = props.size || 'normal';
nit: can you add this to the destructed props above?

2024-06-21 14:35 UTC, dreamwasp commented on packages/gamut/src/Button/IconButton.tsx
> +      large: 40,
nit: add to styles folder, i think it makes more sense to be there

2024-06-21 14:35 UTC, dreamwasp commented on packages/gamut/src/Button/IconButton.tsx
> +          <Icon size={iconSize} />
can you re-add aria-hidden here?

2024-06-21 14:36 UTC, dreamwasp requested changes
just blocking till aria-hidden is added back, otherwise looks great!

2024-06-21 15:44 UTC, LinKCoding commented on packages/gamut/src/Button/IconButton.tsx
> +          <Icon size={iconSize} />
woops, thanks!

2024-06-21 15:51 UTC, LinKCoding commented on packages/gamut/src/Button/IconButton.tsx
> +    const size = props.size || 'normal';
can do!

2024-06-21 15:54 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.5-alpha.f134e0.0<br/>@codecademy/gamut-kit@0.6.417-alpha.f134e0.0<br/>@codecademy/styleguide@66.25.2-alpha.f134e0.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-21 15:56 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6675a2a6803efaa9e7dbf1b0--gamut-preview.netlify.app>https://6675a2a6803efaa9e7dbf1b0--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6675a2a6803efaa9e7dbf1b0>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-21 16:26 UTC, dreamwasp approved these changes

2024-06-21 20:15 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.6-alpha.636d8b.0<br/>@codecademy/gamut-kit@0.6.418-alpha.636d8b.0<br/>@codecademy/styleguide@66.26.1-alpha.636d8b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-21 20:17 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6675dfd6af420307ed07c73c--gamut-preview.netlify.app>https://6675dfd6af420307ed07c73c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6675dfd6af420307ed07c73c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-21 20:47 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.6-alpha.636d8b.0<br/>@codecademy/gamut-kit@0.6.418-alpha.636d8b.0<br/>@codecademy/styleguide@66.26.1-alpha.636d8b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-21 21:08 UTC, LinKCoding commented
@dreamwasp ah wait -- I remember why I took out `aria-hidden`, Icon should come with aria-hidden true already, so I just removed it here because it wasn't needed. 

I added it to IconButtonBase weirdly 🤔 (and it's breaking some tests lol) 

gonna fix that now, but we can also disc on Monday. Thanks!

2024-06-21 21:16 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@55.22.6-alpha.7a40b3.0<br/>@codecademy/gamut-kit@0.6.418-alpha.7a40b3.0<br/>@codecademy/styleguide@66.26.1-alpha.7a40b3.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-06-21 21:19 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://6675ee49b8e00cf6bd9863e6--gamut-preview.netlify.app>https://6675ee49b8e00cf6bd9863e6--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/6675ee49b8e00cf6bd9863e6>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-06-24 14:17 UTC, dreamwasp commented
> @dreamwasp ah wait -- I remember why I took out `aria-hidden`, Icon should come with aria-hidden true already, so I just removed it here because it wasn't needed.
> 
> I added it to IconButtonBase weirdly 🤔 (and it's breaking some tests lol)
> 
> gonna fix that now, but we can also disc on Monday. Thanks!

oh duh!!! you're totally right. this is perfect ✨

2024-06-24 14:17 UTC, dreamwasp approved these changes

2024-06-24 14:38 UTC, merged