feat(BorderRadius token)!: Adding a border radius scale
Codecademy/gamut pull request #2918
Opened 2024-08-02 20:11 UTC by LinKCoding

### Overview

### PR Checklist

- [ ] Related to designs:
- [ ] Related to JIRA ticket: [ABC-123]
- [ ] I have run this code to verify it works
- [ ] This PR includes unit tests for the code change
- [ ] This PR includes testing instructions tests for the code change
- [ ] The alpha package of this PR is passing end-to-end tests in all relevant Codecademy repositories

#### Testing Instructions

[Don't make me tap the sign.](https://i.imgur.com/sy93D9I.png)

#### PR Links and Envs

| Repository   | PR Link                                                  | PR Env                                                   |
| :----------- | :------------------------------------------------------- | :------------------------------------------------------- |
| Monolith     | [Monolith PR](http://www.google.fr/ 'Named link title')  | [Monolith Env](http://www.google.fr/ 'Named link title') |
| Portal       | [Portal Link](http://www.google.fr/ 'Named link title')  | [Portal Env](http://www.google.fr/ 'Named link title')   |
| Another Repo | [Another Link](http://www.google.fr/ 'Named link title') | [Another Env](http://www.google.fr/ 'Named link title')  |

2024-08-06 13:31 UTC, dreamwasp commented on packages/gamut-styles/src/variables/borderRadii.ts
> +  xLarge: '16px',
i've been thinking about these (and sorry for not saying this before your conversion PRs -_-#) but i think we should rename the keys here to `0`, `2`, `4`, `8`, `16`, `50%` or `none`, `sm`, `m`, `l`, `xl`, `full` to match the token names for [spacing](https://gamut.codecademy.com/?path=/docs/foundations-theme--colors#space) or [media-queries ](https://gamut.codecademy.com/?path=/docs/foundations-theme--colors#space). i think i prefer the none/sm/m/l/xl/full since that aligns to the figma more

2024-08-06 13:39 UTC, LinKCoding commented on packages/gamut-styles/src/variables/borderRadii.ts
> +  xLarge: '16px',
that makes a lot of sense, I'll update!

2024-08-06 15:28 UTC, LinKCoding commented on packages/gamut/src/Card/index.tsx
> +        borderRadius="m"
Adding this in b.c. for shadow variants, the border-radius resets to 0

2024-08-06 15:30 UTC, LinKCoding commented on packages/gamut/src/Video/styles/index.module.scss
> +  overflow: hidden;
This rounds out the corners for a video player, however since it's using .scss it doesn't use tokens

2024-08-06 20:57 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.976eda.0<br/>@codecademy/gamut-icons@9.29.2-alpha.976eda.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.976eda.0<br/>@codecademy/gamut-kit@0.6.434-alpha.976eda.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.976eda.0<br/>@codecademy/gamut-styles@16.3.1-alpha.976eda.0<br/>@codecademy/gamut-tests@5.1.1-alpha.976eda.0<br/>@codecademy/styleguide@68.0.0-alpha.976eda.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-06 20:59 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b28eb99bd1ab6b4ff66db5--gamut-preview.netlify.app>https://66b28eb99bd1ab6b4ff66db5--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b28eb99bd1ab6b4ff66db5>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-06 21:12 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.2e8e59.0<br/>@codecademy/gamut-icons@9.29.2-alpha.2e8e59.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.2e8e59.0<br/>@codecademy/gamut-kit@0.6.434-alpha.2e8e59.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.2e8e59.0<br/>@codecademy/gamut-styles@16.3.1-alpha.2e8e59.0<br/>@codecademy/gamut-tests@5.1.1-alpha.2e8e59.0<br/>@codecademy/styleguide@68.0.0-alpha.2e8e59.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-06 21:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b292254ce5c56d79c97537--gamut-preview.netlify.app>https://66b292254ce5c56d79c97537--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b292254ce5c56d79c97537>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-06 21:56 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.353249.0<br/>@codecademy/gamut-icons@9.29.2-alpha.353249.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.353249.0<br/>@codecademy/gamut-kit@0.6.434-alpha.353249.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.353249.0<br/>@codecademy/gamut-styles@16.3.1-alpha.353249.0<br/>@codecademy/gamut-tests@5.1.1-alpha.353249.0<br/>@codecademy/styleguide@68.0.0-alpha.353249.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-06 21:57 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b29c5ad354ea06a33f34e2--gamut-preview.netlify.app>https://66b29c5ad354ea06a33f34e2--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b29c5ad354ea06a33f34e2>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-06 23:26 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.286032.0<br/>@codecademy/gamut-icons@9.29.2-alpha.286032.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.286032.0<br/>@codecademy/gamut-kit@0.6.434-alpha.286032.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.286032.0<br/>@codecademy/gamut-styles@16.3.1-alpha.286032.0<br/>@codecademy/gamut-tests@5.1.1-alpha.286032.0<br/>@codecademy/styleguide@68.0.0-alpha.286032.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-06 23:28 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b2b17ef99cc20d6dc76a7c--gamut-preview.netlify.app>https://66b2b17ef99cc20d6dc76a7c--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b2b17ef99cc20d6dc76a7c>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-07 14:50 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b389b399645d008c3ffad1--gamut-preview.netlify.app>https://66b389b399645d008c3ffad1--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b389b399645d008c3ffad1>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-08 14:34 UTC, aresnik11 commented on packages/gamut-styles/src/variables/borderRadii.ts
> +  l: '8px',
for other breakpoints we use `md` and `lg`, should this be consistent?

2024-08-08 14:38 UTC, aresnik11 commented on packages/gamut/src/Form/SelectDropdown/styles.ts
> +      borderRadius: `0px 4px 4px 0px` as const, // only want border radius on top and bottom right
can/should this be using the new tokens `borderRadiusTopRight` and `borderRadiusBottomRight`?

2024-08-08 14:41 UTC, aresnik11 commented on packages/gamut/src/Tag/elements.tsx
> +      borderRadius: borderRadiusStyle as any,
could this instead be
```
borderRadiusTopRight: 'm'
borderRadiusBottomRight: 'm'
```
and we can avoid the `as any`?

2024-08-09 14:36 UTC, LinKCoding commented on packages/gamut-styles/src/variables/borderRadii.ts
> +  l: '8px',
that makes a lot of sense lol, let me make those changes!

2024-08-09 14:36 UTC, LinKCoding commented on packages/gamut/src/Tag/elements.tsx
> +      borderRadius: borderRadiusStyle as any,
ooo that makes sense :) I'll try that out!

2024-08-09 15:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.d1fa10.0<br/>@codecademy/gamut-icons@9.29.2-alpha.d1fa10.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.d1fa10.0<br/>@codecademy/gamut-kit@0.6.434-alpha.d1fa10.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.d1fa10.0<br/>@codecademy/gamut-styles@16.3.1-alpha.d1fa10.0<br/>@codecademy/gamut-tests@5.1.1-alpha.d1fa10.0<br/>@codecademy/styleguide@68.0.0-alpha.d1fa10.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-09 15:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b634dda3dcf120f7b48441--gamut-preview.netlify.app>https://66b634dda3dcf120f7b48441--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b634dda3dcf120f7b48441>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-09 15:39 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.47b6ec.0<br/>@codecademy/gamut-icons@9.30.1-alpha.47b6ec.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.47b6ec.0<br/>@codecademy/gamut-kit@0.6.435-alpha.47b6ec.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.47b6ec.0<br/>@codecademy/gamut-styles@16.3.1-alpha.47b6ec.0<br/>@codecademy/gamut-tests@5.1.1-alpha.47b6ec.0<br/>@codecademy/styleguide@68.0.0-alpha.47b6ec.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-09 15:41 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66b638aba5564d138d26762f--gamut-preview.netlify.app>https://66b638aba5564d138d26762f--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66b638aba5564d138d26762f>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-12 20:59 UTC, dreamwasp requested changes
all looks great to me! just pending approval until the integration PRs are sorted

2024-08-16 19:06 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.004197.0<br/>@codecademy/gamut-icons@9.30.1-alpha.004197.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.004197.0<br/>@codecademy/gamut-kit@0.6.435-alpha.004197.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.004197.0<br/>@codecademy/gamut-styles@16.3.1-alpha.004197.0<br/>@codecademy/gamut-tests@5.1.1-alpha.004197.0<br/>@codecademy/styleguide@68.0.0-alpha.004197.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-16 19:08 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66bfa3941f5823929fd6f5c3--gamut-preview.netlify.app>https://66bfa3941f5823929fd6f5c3--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66bfa3941f5823929fd6f5c3>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-16 19:23 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.75e367.0<br/>@codecademy/gamut-icons@9.30.1-alpha.75e367.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.75e367.0<br/>@codecademy/gamut-kit@0.6.437-alpha.75e367.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.75e367.0<br/>@codecademy/gamut-styles@16.3.1-alpha.75e367.0<br/>@codecademy/gamut-tests@5.1.1-alpha.75e367.0<br/>@codecademy/styleguide@68.0.0-alpha.75e367.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-16 19:25 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66bfa78e50dbc68a161e1e45--gamut-preview.netlify.app>https://66bfa78e50dbc68a161e1e45--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66bfa78e50dbc68a161e1e45>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-16 19:43 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.65eb46.0<br/>@codecademy/gamut-icons@9.30.1-alpha.65eb46.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.65eb46.0<br/>@codecademy/gamut-kit@0.6.437-alpha.65eb46.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.65eb46.0<br/>@codecademy/gamut-styles@16.3.1-alpha.65eb46.0<br/>@codecademy/gamut-tests@5.1.1-alpha.65eb46.0<br/>@codecademy/styleguide@68.0.0-alpha.65eb46.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-16 19:46 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66bfac85f0169f956e26608d--gamut-preview.netlify.app>https://66bfac85f0169f956e26608d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66bfac85f0169f956e26608d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-21 15:14 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66c60452cde1b81c7d0e0b4d--gamut-preview.netlify.app>https://66c60452cde1b81c7d0e0b4d--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66c60452cde1b81c7d0e0b4d>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-21 20:38 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.a9f74b.0<br/>@codecademy/gamut-icons@9.30.1-alpha.a9f74b.0<br/>@codecademy/gamut-illustrations@0.46.1-alpha.a9f74b.0<br/>@codecademy/gamut-kit@0.6.437-alpha.a9f74b.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.a9f74b.0<br/>@codecademy/gamut-styles@16.3.1-alpha.a9f74b.0<br/>@codecademy/gamut-tests@5.1.1-alpha.a9f74b.0<br/>@codecademy/styleguide@68.0.0-alpha.a9f74b.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-21 20:40 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66c650c116ff688f5b779787--gamut-preview.netlify.app>https://66c650c116ff688f5b779787--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66c650c116ff688f5b779787>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->

2024-08-27 14:17 UTC, dreamwasp approved these changes

2024-08-27 14:22 UTC, codecademydev commented
<h3>📬Published Alpha Packages:</h3><pre>@codecademy/gamut@57.0.0-alpha.8bfb44.0<br/>@codecademy/gamut-icons@9.30.1-alpha.8bfb44.0<br/>@codecademy/gamut-illustrations@0.47.1-alpha.8bfb44.0<br/>@codecademy/gamut-kit@0.6.439-alpha.8bfb44.0<br/>@codecademy/gamut-patterns@0.9.14-alpha.8bfb44.0<br/>@codecademy/gamut-styles@16.3.1-alpha.8bfb44.0<br/>@codecademy/gamut-tests@5.1.1-alpha.8bfb44.0<br/>@codecademy/styleguide@68.0.0-alpha.8bfb44.0<br/></pre><!--LERNA_VERSION_COMMENT-->

2024-08-27 14:24 UTC, merged

2024-08-27 14:24 UTC, codecademydev commented
<p>🚀 Styleguide deploy preview ready!</p><p><a href=https://66cde19921541118a9de0bc4--gamut-preview.netlify.app>https://66cde19921541118a9de0bc4--gamut-preview.netlify.app</a></p><p><a href=https://app.netlify.com/sites/gamut-preview/deploys/66cde19921541118a9de0bc4>Deploy Logs</a></p><!--ALPHA_DEPLOY_COMMENT-->